{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.4.1/lib-0.4.1.module",
    "group": "com.glureau.k2d",
    "module": "lib",
    "version": "0.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-macosarm64-0.4.1.klib",
          "size": 9103,
          "sha512": "9eaf764e76c39b96448241a60b78c12aadf5a8e939461de6a8c852262fe87977f880c9cb8cc175aa8149fbadc4fa09b04f3682b3baf0d550e8e6a8e558f3f96f",
          "sha256": "3df1f1f0ac9a20599cbf97182e9f41d49ff1252a7445d6746b2a900fd7d6d24f",
          "sha1": "d02f2971dd05bf08a22857dccdc568959e6c23be",
          "md5": "3d946b64ba0713393e4b4f2c00b24112"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-macosarm64-0.4.1-metadata.jar",
          "url": "lib-macosarm64-0.4.1-metadata.jar",
          "size": 261,
          "sha512": "c7c138fbcdfda9cb2c559f8964c6776f5ffccda52d5973fcdda70387be095b096b4c581f2ae318f793991a8a6776b0904d9f87e52df58943d5c121cca2cb244e",
          "sha256": "153392f46865dd5033b9a2a1f7a87d147838ede6248bb22f7402f3a629070546",
          "sha1": "f4c48cd1dc973a25fd71144de7665bd3487625ca",
          "md5": "0201b95427e5f927c5f5d3e8185f8224"
        }
      ]
    }
  ]
}
