{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.4.0/lib-0.4.0.module",
    "group": "com.glureau.k2d",
    "module": "lib",
    "version": "0.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-release.aar",
          "url": "lib-android-0.4.0.aar",
          "size": 5217,
          "sha512": "2f5e8fa31986c65134e5cedc632e156098c3fc5248c2d25e124186892475b36be271ce48faf432b11e96ac06679faa2ca5d7c2004d8c6569414d40918e6c637d",
          "sha256": "e899051ea370f98cd187bb3d833421e4db8a83da513c75734202c151ffd17894",
          "sha1": "79f73db4d800798af3184bd2aa479624fd4f21fd",
          "md5": "1810928a639859db870105c82f7c8125"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "lib-release.aar",
          "url": "lib-android-0.4.0.aar",
          "size": 5217,
          "sha512": "2f5e8fa31986c65134e5cedc632e156098c3fc5248c2d25e124186892475b36be271ce48faf432b11e96ac06679faa2ca5d7c2004d8c6569414d40918e6c637d",
          "sha256": "e899051ea370f98cd187bb3d833421e4db8a83da513c75734202c151ffd17894",
          "sha1": "79f73db4d800798af3184bd2aa479624fd4f21fd",
          "md5": "1810928a639859db870105c82f7c8125"
        }
      ]
    }
  ]
}
