{
  "formatVersion": "1.1",
  "component": {
    "group": "com.glureau.k2d",
    "module": "gradle-plugin",
    "version": "0.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.glureau.k2d",
          "module": "compiler",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-plugin-0.4.2.jar",
          "url": "gradle-plugin-0.4.2.jar",
          "size": 7004,
          "sha512": "d463f58fde68fa34775dd1a87e5898f4c5f89c07af3a1d05881276eaf028c522a1f61456dd16bee7f3e14dffd8d003f5d7600a808f1a1376c5cfad127bef0ba1",
          "sha256": "56278c87d1c7586cb02200aed008cf1f894a4f65b2f38cedd14dc9454d09b82a",
          "sha1": "de081197d0c9ba43dd37e8217f0f2e96c8e06a61",
          "md5": "65a2f08f07da1123fc54617d46d461d9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-gradle-plugin",
          "version": {
            "requires": "1.8.10-1.0.9"
          }
        },
        {
          "group": "com.glureau.k2d",
          "module": "lib",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "com.glureau.k2d",
          "module": "compiler",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-plugin-0.4.2.jar",
          "url": "gradle-plugin-0.4.2.jar",
          "size": 7004,
          "sha512": "d463f58fde68fa34775dd1a87e5898f4c5f89c07af3a1d05881276eaf028c522a1f61456dd16bee7f3e14dffd8d003f5d7600a808f1a1376c5cfad127bef0ba1",
          "sha256": "56278c87d1c7586cb02200aed008cf1f894a4f65b2f38cedd14dc9454d09b82a",
          "sha1": "de081197d0c9ba43dd37e8217f0f2e96c8e06a61",
          "md5": "65a2f08f07da1123fc54617d46d461d9"
        }
      ]
    }
  ]
}
