{
  "formatVersion": "1.1",
  "component": {
    "group": "com.glureau.k2d",
    "module": "compiler",
    "version": "0.4.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "compiler-0.4.4.jar",
          "url": "compiler-0.4.4.jar",
          "size": 164098,
          "sha512": "a0e72d6d715b3b9aff748427b810111fabc672d417a6ba0742c2abedd2d7c1bda5e5bdae14328fe38b2d7705afe487188f058fa2d34208f9bbc539eb5d49e167",
          "sha256": "2fe315780a6f8f41b8ed44e82512b22331f0b62a731b583431d67c30043c453d",
          "sha1": "42f2c618e299674021b69e91e74523f14eebebb2",
          "md5": "e471b58a0f28fbccbb7c9d9fdda35aa8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.glureau.k2d",
          "module": "lib",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-ksp",
          "version": {
            "requires": "1.14.2"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing",
          "version": {
            "requires": "1.8.10-1.0.9"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "1.8.10-1.0.9"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "compiler-0.4.4.jar",
          "url": "compiler-0.4.4.jar",
          "size": 164098,
          "sha512": "a0e72d6d715b3b9aff748427b810111fabc672d417a6ba0742c2abedd2d7c1bda5e5bdae14328fe38b2d7705afe487188f058fa2d34208f9bbc539eb5d49e167",
          "sha256": "2fe315780a6f8f41b8ed44e82512b22331f0b62a731b583431d67c30043c453d",
          "sha1": "42f2c618e299674021b69e91e74523f14eebebb2",
          "md5": "e471b58a0f28fbccbb7c9d9fdda35aa8"
        }
      ]
    }
  ]
}
