{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.3.0/lib-0.3.0.module",
    "group": "com.glureau.k2d",
    "module": "lib",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-tvosx64-0.3.0.klib",
          "size": 9066,
          "sha512": "ea7c816c46c1abd801438c60ddbfd45226e2cfd40950df7e4aa6c3cf6e046ec5c21c7fd2b7dde1e3db47b4b642edd0e2b29f1e7facf2c1b093e215ebd17c2b5e",
          "sha256": "a39f7d2c81ea9b0de89bae8acbdd717c0bde2dde5e6cb78c847767e67a41d34e",
          "sha1": "cfbdf8e1b3546675d1de54d94d5750dae6a2059e",
          "md5": "871a6b8f71099d7a219ac45b9cfe6844"
        }
      ]
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib-tvosx64-0.3.0-metadata.jar",
          "url": "lib-tvosx64-0.3.0-metadata.jar",
          "size": 261,
          "sha512": "a14eeeed085439bd4a886dc4861b98237d6707494dbe2b22dce8463de5980face8a59612dd2e81eba430518ecaf4bf5b9c9addea1756956a6144eb896ac6b5c0",
          "sha256": "7e4afbd685ee8cea72d0e93b5040d2cb0c47e368f18141db96c8792b50b3902e",
          "sha1": "1e016192da7e5c2a43420ba6ee19b75cbe89a7cd",
          "md5": "7c73b719aab8c868e6cec41883239425"
        }
      ]
    }
  ]
}
