{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.3.0/lib-0.3.0.module",
    "group": "com.glureau.k2d",
    "module": "lib",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-tvosx64-0.3.0.klib",
          "size": 9066,
          "sha512": "ea7c816c46c1abd801438c60ddbfd45226e2cfd40950df7e4aa6c3cf6e046ec5c21c7fd2b7dde1e3db47b4b642edd0e2b29f1e7facf2c1b093e215ebd17c2b5e",
          "sha256": "a39f7d2c81ea9b0de89bae8acbdd717c0bde2dde5e6cb78c847767e67a41d34e",
          "sha1": "cfbdf8e1b3546675d1de54d94d5750dae6a2059e",
          "md5": "871a6b8f71099d7a219ac45b9cfe6844"
        }
      ]
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib-tvosx64-0.3.0-metadata.jar",
          "url": "lib-tvosx64-0.3.0-metadata.jar",
          "size": 261,
          "sha512": "9582ea60474d758f445dd8b1abfc9ca9d04d1dda40dab098fd974a19cd1b6fa13e0e26e1c8e9287db2b6eeccce35bbc0613a828480d9159cee8ed69ca6c4b798",
          "sha256": "1cd94d3c25f96bdfbbe48ac81c63c4f5a1d195142f08c1de91b3c835d3060e97",
          "sha1": "9f7588014bd5218a56239ee32ecee4895974af97",
          "md5": "3708c260ae075e93f201b000093d35b5"
        }
      ]
    }
  ]
}
