{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.4.0/lib-0.4.0.module",
    "group": "com.glureau.k2d",
    "module": "lib",
    "version": "0.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-debug.aar",
          "url": "lib-android-debug-0.4.0.aar",
          "size": 5257,
          "sha512": "990f0674d2c17323bbca5e0d0c52ae71ac68588c1f81ab0c712e66f7b1e4a5e784257f5c3de031e294aae410627092c6243593f816c365a0e71acee511b400cb",
          "sha256": "43ed9dcac66e3b836bc9fef2ec1f2bed6030ece99a1d7aaccb33bab8b362dc5f",
          "sha1": "9c10f47b1d9ff61e6384d9219e5529b353c00724",
          "md5": "f68197b6b3d4d5a23828b16944b00038"
        }
      ]
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "lib-debug.aar",
          "url": "lib-android-debug-0.4.0.aar",
          "size": 5257,
          "sha512": "990f0674d2c17323bbca5e0d0c52ae71ac68588c1f81ab0c712e66f7b1e4a5e784257f5c3de031e294aae410627092c6243593f816c365a0e71acee511b400cb",
          "sha256": "43ed9dcac66e3b836bc9fef2ec1f2bed6030ece99a1d7aaccb33bab8b362dc5f",
          "sha1": "9c10f47b1d9ff61e6384d9219e5529b353c00724",
          "md5": "f68197b6b3d4d5a23828b16944b00038"
        }
      ]
    }
  ]
}
