{
  "formatVersion": "1.1",
  "component": {
    "group": "com.glureau.k2d",
    "module": "compiler",
    "version": "0.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "compiler-0.4.0.jar",
          "url": "compiler-0.4.0.jar",
          "size": 160723,
          "sha512": "f07a79212cffaf6f4ecff1bb7c03a01be692464db7fc6e868a82ffc6a93a7a3151441802e1e537a9c3f0cfe7cfc76e7fd7ac148c787ee0e0ca492ab723c4a178",
          "sha256": "9a203d830b5513e612564b87204a0764ce8be4fbe9f920fba010d116d743adeb",
          "sha1": "ce2db033e7471fd117904c9686ac0b7567d7da7e",
          "md5": "7e5cf07183526b8450a09a482cb13c7a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.glureau.k2d",
          "module": "lib",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-ksp",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing",
          "version": {
            "requires": "1.8.0-1.0.9"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "1.8.0-1.0.9"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "compiler-0.4.0.jar",
          "url": "compiler-0.4.0.jar",
          "size": 160723,
          "sha512": "f07a79212cffaf6f4ecff1bb7c03a01be692464db7fc6e868a82ffc6a93a7a3151441802e1e537a9c3f0cfe7cfc76e7fd7ac148c787ee0e0ca492ab723c4a178",
          "sha256": "9a203d830b5513e612564b87204a0764ce8be4fbe9f920fba010d116d743adeb",
          "sha1": "ce2db033e7471fd117904c9686ac0b7567d7da7e",
          "md5": "7e5cf07183526b8450a09a482cb13c7a"
        }
      ]
    }
  ]
}
