{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.3.0/lib-0.3.0.module",
    "group": "com.glureau.k2d",
    "module": "lib",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-tvosarm64-0.3.0.klib",
          "size": 9083,
          "sha512": "f62974297bb67b0a2438336b844baa8e8850ec7f0d6f1a77b5d73e238b2d8fd3eb3c2024123cf4b80460a0d0de8e3494eb89a3e821fff2b5bd6f48278ba9d288",
          "sha256": "1dbf7bb6b683748612f761f58d5d136c01b80f8ea6e69114a77e6677045c6783",
          "sha1": "1b898dcc53c2aa8a465a835f788188da853da301",
          "md5": "bb49dda8b44562f6ac10523bf5d68336"
        }
      ]
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib-tvosarm64-0.3.0-metadata.jar",
          "url": "lib-tvosarm64-0.3.0-metadata.jar",
          "size": 261,
          "sha512": "f6331daba2c897e01d001eec2db1f2261996d708d5e6b31e83fe66a8c516a9322f813a31393567106299e068fa05f6b53d98272cf8e76232108af99271a72fac",
          "sha256": "b5944e7adba91ba0e1a468f4a2494420f25d267f1fbc67f422572ff5a5e0f38a",
          "sha1": "7e2cc8acc5b4bb9fdad9160857d5c4bb22c75c44",
          "md5": "337ab37aeb55452156edda365c1c7eab"
        }
      ]
    }
  ]
}
