{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.3.0/lib-0.3.0.module",
    "group": "com.glureau.k2d",
    "module": "lib",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-tvosarm64-0.3.0.klib",
          "size": 9083,
          "sha512": "f62974297bb67b0a2438336b844baa8e8850ec7f0d6f1a77b5d73e238b2d8fd3eb3c2024123cf4b80460a0d0de8e3494eb89a3e821fff2b5bd6f48278ba9d288",
          "sha256": "1dbf7bb6b683748612f761f58d5d136c01b80f8ea6e69114a77e6677045c6783",
          "sha1": "1b898dcc53c2aa8a465a835f788188da853da301",
          "md5": "bb49dda8b44562f6ac10523bf5d68336"
        }
      ]
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib-tvosarm64-0.3.0-metadata.jar",
          "url": "lib-tvosarm64-0.3.0-metadata.jar",
          "size": 261,
          "sha512": "4b190a7a41496e9acaeaccfef2d487bdbe172278a505d65b56bfb8e7c38a55efcc86d3e79e63d92fa8a60a33f80b71ce21f69bc25a48b6fb4a276a7087039ba0",
          "sha256": "d3869dae84ca59458f311371496cf6e697d887c0ff29b2477caf786dcbafddd6",
          "sha1": "7a7f4a0978f04541ae4d1ab9be08cc5bbbca7776",
          "md5": "d3c3faf956915a207d3542b793d67edd"
        }
      ]
    }
  ]
}
