{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.4.0/lib-0.4.0.module",
    "group": "com.glureau.k2d",
    "module": "lib",
    "version": "0.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-tvosarm64-0.4.0.klib",
          "size": 9094,
          "sha512": "fce4aa70f20a0df70ecdbc79f825e44cfbf97d85158dd0d8ccfc26239eece5f5e21c31e85dc6933d9e20da913f81b3d86070aa69a5d9a0b8bbd889fb666b19bd",
          "sha256": "c5be0b785fd3d3337b83062f396ca70a02b6cf6ba81a1d15e1d9deda5b8addb6",
          "sha1": "b97728bbf34b2bec442c11edee4e38957b472899",
          "md5": "003fa4b40128ef9d83fe97436075a7cc"
        }
      ]
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-tvosarm64-0.4.0-metadata.jar",
          "url": "lib-tvosarm64-0.4.0-metadata.jar",
          "size": 261,
          "sha512": "b2013d6dffaae7638dbcd447c7a633d5f1095b764d874bc92e51e1b01bcbd2866d9e00427f4a82407fb2fe46a626c7cfa249d0e774b79d96f95ba200b536d8d7",
          "sha256": "b0fb28611899eb3e18a824bfd6ceb4b83ea6c4066bce86b9f08563ef6bf7f4ca",
          "sha1": "5a894a20fd6eb2dab9a9e697b808b284adc9f89a",
          "md5": "2d13c78bd9962ac79f376aa26b75c1cf"
        }
      ]
    }
  ]
}
