{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.1.0/lib-0.1.0.module",
    "group": "com.glureau.mermaidksp",
    "module": "lib",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "lib-jvm-0.1.0.jar",
          "url": "lib-jvm-0.1.0.jar",
          "size": 1506,
          "sha512": "6d4adf454a973f476989a70f68c18a4fe21bc18d0b4d8abfaee458eabe5a4fe33f7ccba629fccb50bf9c1b037e39738352731cf0b6515ce03f3abf58ce5874a2",
          "sha256": "17d171bf5eab6ec58e4b4c9851cf9ad0a821199ae7e41924c38a277e0be4b105",
          "sha1": "98164ba999e7f0c3b1dc6490e9402beb4146bf19",
          "md5": "9a506c3ff4aff0d252df7db4980740e3"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "lib-jvm-0.1.0.jar",
          "url": "lib-jvm-0.1.0.jar",
          "size": 1506,
          "sha512": "6d4adf454a973f476989a70f68c18a4fe21bc18d0b4d8abfaee458eabe5a4fe33f7ccba629fccb50bf9c1b037e39738352731cf0b6515ce03f3abf58ce5874a2",
          "sha256": "17d171bf5eab6ec58e4b4c9851cf9ad0a821199ae7e41924c38a277e0be4b105",
          "sha1": "98164ba999e7f0c3b1dc6490e9402beb4146bf19",
          "md5": "9a506c3ff4aff0d252df7db4980740e3"
        }
      ]
    }
  ]
}
