{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.3.0/lib-0.3.0.module",
    "group": "com.glureau.k2d",
    "module": "lib",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-macosarm64-0.3.0.klib",
          "size": 9092,
          "sha512": "e1608c979ab128f6e62f0276994a4fa18ef23d37db3f29d2648928a2fcca5d90002c6e1ea0ae14bafa8d6c2504c30bb804a985eaef0e861ea91432daae5ecf5c",
          "sha256": "66266dcf438e7b6254516e58763799e937a03dfb3f6f0d498a03fb45cd98229f",
          "sha1": "8198a7b47d1f6081011ac82900522e745b7fe555",
          "md5": "b7eb7d4a3f26e903da6062482d582c99"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib-macosarm64-0.3.0-metadata.jar",
          "url": "lib-macosarm64-0.3.0-metadata.jar",
          "size": 261,
          "sha512": "9ff62b17ca353cc716f33401535ecec0d5befdd748bf2711e31238b3c479c8e8028e9913711e224a111240edeb6a4d277be3c278b1424c1d288aa2a4ac3f16fa",
          "sha256": "2ebfa0a792a5ac89ae4ad0f817f961f72182b27cbafb6bf0ca5bf0b9b3e584a7",
          "sha1": "756c9036382dbd6efeb63ea75aedc318aef8cbcc",
          "md5": "a4679be8c044590a9ace222bfa87e579"
        }
      ]
    }
  ]
}
