{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.3.0/lib-0.3.0.module",
    "group": "com.glureau.k2d",
    "module": "lib",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-macosarm64-0.3.0.klib",
          "size": 9092,
          "sha512": "e1608c979ab128f6e62f0276994a4fa18ef23d37db3f29d2648928a2fcca5d90002c6e1ea0ae14bafa8d6c2504c30bb804a985eaef0e861ea91432daae5ecf5c",
          "sha256": "66266dcf438e7b6254516e58763799e937a03dfb3f6f0d498a03fb45cd98229f",
          "sha1": "8198a7b47d1f6081011ac82900522e745b7fe555",
          "md5": "b7eb7d4a3f26e903da6062482d582c99"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib-macosarm64-0.3.0-metadata.jar",
          "url": "lib-macosarm64-0.3.0-metadata.jar",
          "size": 261,
          "sha512": "35803811958ac8a70610382732564ca89a88c34d2b1e81b4dcc6227cd7cacb7919b36cd7efad1807dc66731ccae127b5cb58534072b513b13471e29e90265d83",
          "sha256": "0c35df1166e7b51b21dbbb651559e67709b2b0adf2e03239beca38a3aa388b39",
          "sha1": "1f2066ca0640fed79de807fc56bc7fd8bf12f754",
          "md5": "c1e02a2cd85c74d26158270ac60c149f"
        }
      ]
    }
  ]
}
