{
  "formatVersion": "1.1",
  "component": {
    "group": "com.glureau.k2d",
    "module": "compiler",
    "version": "0.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "compiler-0.4.2.jar",
          "url": "compiler-0.4.2.jar",
          "size": 162193,
          "sha512": "ce5f806a44414eac3d488ee6376215e8085464e18c27ba02147bd5819b0159a99864c1ac3194db4ebb98758759792b1a9d0feb9a4c98faa5aacf0e3114dde219",
          "sha256": "ae880f610ed29619815593152a4b1a44268fc4144470b84f1f77b13779fd9e58",
          "sha1": "8e36d65353845302d6fcbbd660f51777261ec4a1",
          "md5": "05c24481fbe33c427fc03c48c1d40334"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.glureau.k2d",
          "module": "lib",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-ksp",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing",
          "version": {
            "requires": "1.8.10-1.0.9"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "1.8.10-1.0.9"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "compiler-0.4.2.jar",
          "url": "compiler-0.4.2.jar",
          "size": 162193,
          "sha512": "ce5f806a44414eac3d488ee6376215e8085464e18c27ba02147bd5819b0159a99864c1ac3194db4ebb98758759792b1a9d0feb9a4c98faa5aacf0e3114dde219",
          "sha256": "ae880f610ed29619815593152a4b1a44268fc4144470b84f1f77b13779fd9e58",
          "sha1": "8e36d65353845302d6fcbbd660f51777261ec4a1",
          "md5": "05c24481fbe33c427fc03c48c1d40334"
        }
      ]
    }
  ]
}
