{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.4.0/lib-0.4.0.module",
    "group": "com.glureau.k2d",
    "module": "lib",
    "version": "0.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-macosarm64-0.4.0.klib",
          "size": 9103,
          "sha512": "9eaf764e76c39b96448241a60b78c12aadf5a8e939461de6a8c852262fe87977f880c9cb8cc175aa8149fbadc4fa09b04f3682b3baf0d550e8e6a8e558f3f96f",
          "sha256": "3df1f1f0ac9a20599cbf97182e9f41d49ff1252a7445d6746b2a900fd7d6d24f",
          "sha1": "d02f2971dd05bf08a22857dccdc568959e6c23be",
          "md5": "3d946b64ba0713393e4b4f2c00b24112"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-macosarm64-0.4.0-metadata.jar",
          "url": "lib-macosarm64-0.4.0-metadata.jar",
          "size": 261,
          "sha512": "b2013d6dffaae7638dbcd447c7a633d5f1095b764d874bc92e51e1b01bcbd2866d9e00427f4a82407fb2fe46a626c7cfa249d0e774b79d96f95ba200b536d8d7",
          "sha256": "b0fb28611899eb3e18a824bfd6ceb4b83ea6c4066bce86b9f08563ef6bf7f4ca",
          "sha1": "5a894a20fd6eb2dab9a9e697b808b284adc9f89a",
          "md5": "2d13c78bd9962ac79f376aa26b75c1cf"
        }
      ]
    }
  ]
}
