{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.4.2/lib-0.4.2.module",
    "group": "com.glureau.k2d",
    "module": "lib",
    "version": "0.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1"
    }
  },
  "variants": [
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-watchosx64-0.4.2.klib",
          "size": 9106,
          "sha512": "1a2322244565c3fc259e3f8aaf86cfa01a196bbfbb06efba9ed310da6f47c83d7547a4f43eba16eef3c381de97f7d1ab217791227ad1f0ecdd6c4ce5ab96112d",
          "sha256": "ba51f7c50a86e84ba40cd1d0f11cdf9d69d5a77ef97ab569b3a8898c042b59f4",
          "sha1": "3c15dcca4e30ea4202157839695345f9ceb72119",
          "md5": "3c08ce9dea58d6789411b734bd47ea1e"
        }
      ]
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib-watchosx64-0.4.2-metadata.jar",
          "url": "lib-watchosx64-0.4.2-metadata.jar",
          "size": 261,
          "sha512": "bf4b022eff77b82597f539bb11fb8878d54293acd96d26ce4ae1533b6482a9f8376feba0b53ba10e2199b56795c96de25c000d93d3b173c698c6abb9ef0e476d",
          "sha256": "cd71a5a2de9a4c797ec10550f1659620f895ccc3caf152018234481dc4304060",
          "sha1": "ac194093a8a6eff2dd17afdb1dbd8b93268724a3",
          "md5": "7bd0b526c863d7bd49a18dbfa5a0ef52"
        }
      ]
    }
  ]
}
