{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.4.0/lib-0.4.0.module",
    "group": "com.glureau.k2d",
    "module": "lib",
    "version": "0.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-js-0.4.0.klib",
          "url": "lib-js-0.4.0.klib",
          "size": 7892,
          "sha512": "4169a97d6ebd84428d67dd1c86d1ee421c849ab82056e0710b08e0d8df003042f0862d8c8111b210846ff91dfefedd0d363d15305d13c3860049fd9442cc0237",
          "sha256": "07cfe56afd354d3fe99fffd0447f47eaebaf9511188e15da4eae7c20ed1b8abe",
          "sha1": "7fed8932ca302d23808fcd4a6ae220a68d36def1",
          "md5": "b8881e2ff81051f3dc411973a6b22a70"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-js-0.4.0.klib",
          "url": "lib-js-0.4.0.klib",
          "size": 7892,
          "sha512": "4169a97d6ebd84428d67dd1c86d1ee421c849ab82056e0710b08e0d8df003042f0862d8c8111b210846ff91dfefedd0d363d15305d13c3860049fd9442cc0237",
          "sha256": "07cfe56afd354d3fe99fffd0447f47eaebaf9511188e15da4eae7c20ed1b8abe",
          "sha1": "7fed8932ca302d23808fcd4a6ae220a68d36def1",
          "md5": "b8881e2ff81051f3dc411973a6b22a70"
        }
      ]
    }
  ]
}
