{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.3.0/lib-0.3.0.module",
    "group": "com.glureau.k2d",
    "module": "lib",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-watchosarm32-0.3.0.klib",
          "size": 9110,
          "sha512": "bc8e39f5f5debcfefb8ac60e9f0a87f04181a07779fea83b090dfea0ad100010bc35cc8d0c10fad03ade5ed83e9a966476b2a22e67db0d79cb3b1f2abd511ba6",
          "sha256": "f9b64a3541a2ca2acad8ad165c4553c60c248c8631a5d97d3bc245b597794616",
          "sha1": "feac127d26bcb5fe3b132fc8943ff2d2a751382a",
          "md5": "48b593033e6247693267690101bdd689"
        }
      ]
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib-watchosarm32-0.3.0-metadata.jar",
          "url": "lib-watchosarm32-0.3.0-metadata.jar",
          "size": 261,
          "sha512": "3413f3f5a2cb9fc6246aec613610b50fe6fe75b5c40d036c8a2ffc449b3752b15184e19f2a97d53b249550cc21a6bb9093564a7a64dc1023cdf4c6831f6852ec",
          "sha256": "351fc06540133cef5741d69ccec3181f9b4ce26393252fb419494583e9181260",
          "sha1": "5ba3a7c4796df12d590e1dc0afa9b5e46c9d232c",
          "md5": "efe590a3aed31cd8f0c0e1ca998228e3"
        }
      ]
    }
  ]
}
