{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.3.0/lib-0.3.0.module",
    "group": "com.glureau.k2d",
    "module": "lib",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-watchosarm32-0.3.0.klib",
          "size": 9110,
          "sha512": "bc8e39f5f5debcfefb8ac60e9f0a87f04181a07779fea83b090dfea0ad100010bc35cc8d0c10fad03ade5ed83e9a966476b2a22e67db0d79cb3b1f2abd511ba6",
          "sha256": "f9b64a3541a2ca2acad8ad165c4553c60c248c8631a5d97d3bc245b597794616",
          "sha1": "feac127d26bcb5fe3b132fc8943ff2d2a751382a",
          "md5": "48b593033e6247693267690101bdd689"
        }
      ]
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib-watchosarm32-0.3.0-metadata.jar",
          "url": "lib-watchosarm32-0.3.0-metadata.jar",
          "size": 261,
          "sha512": "f1ebe4eabc183585083f658db2fe153b1ed25e3006125e0fc07426c590cf55f99c7f1648044cdbddaa10aae740d6ac867017afe65cbff2dd2b20508023ee8320",
          "sha256": "9dd3d889a2813a18770532ac2e60bb7bd8f0de55a4b99ebea6bc0801d132158b",
          "sha1": "0137a2704bb20d8d390a932a946fe818d814bfa7",
          "md5": "095d4fac744d99a5921e394a0185e89a"
        }
      ]
    }
  ]
}
