{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.3.0/lib-0.3.0.module",
    "group": "com.glureau.k2d",
    "module": "lib",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-iossimulatorarm64-0.3.0.klib",
          "size": 9160,
          "sha512": "8227dd45a7fe6035427af1673ce964fe0a5603d358cdfe111f50348e5f13eecce8450f8dc59bb2c98139f13b18ab1d29d2646af6e422db304dd389b365317aae",
          "sha256": "347dc3f8d4ca7400d6a3b48fda89c5aa29e40090e2cc07d280c97400b755e393",
          "sha1": "b0a2114d693beaefe216f09130907e737a75f643",
          "md5": "6110275082ea656efa5084c15cf3ddf6"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib-iossimulatorarm64-0.3.0-metadata.jar",
          "url": "lib-iossimulatorarm64-0.3.0-metadata.jar",
          "size": 261,
          "sha512": "e7a65e379cba036b97a4a6eb026974ca709673bd5bc55fd1123b5472f70c4b4a60bb3a9dca787fdeab8ed438383f43b1d132f01a5a8b5d8b1e8284666897edb0",
          "sha256": "ec4ebc43fc015657f5b3424f63668327adb9874d5d4f9c52a68ae32a5cbf4881",
          "sha1": "cc01b75c6ddda1eb417dd557e31125e7de307d44",
          "md5": "52e7a6c933ac5ecca17527041152e233"
        }
      ]
    }
  ]
}
