{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.3.0/lib-0.3.0.module",
    "group": "com.glureau.k2d",
    "module": "lib",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-iossimulatorarm64-0.3.0.klib",
          "size": 9160,
          "sha512": "8227dd45a7fe6035427af1673ce964fe0a5603d358cdfe111f50348e5f13eecce8450f8dc59bb2c98139f13b18ab1d29d2646af6e422db304dd389b365317aae",
          "sha256": "347dc3f8d4ca7400d6a3b48fda89c5aa29e40090e2cc07d280c97400b755e393",
          "sha1": "b0a2114d693beaefe216f09130907e737a75f643",
          "md5": "6110275082ea656efa5084c15cf3ddf6"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib-iossimulatorarm64-0.3.0-metadata.jar",
          "url": "lib-iossimulatorarm64-0.3.0-metadata.jar",
          "size": 261,
          "sha512": "587ddb0aea9f3ee4d073b62f8e6664cdb4477be96b93531adf43a7cb6ef362d52e71054c0f2bedebb605ca8df9434a1a5bc4924b6cebafad29ae148e66c6c2e3",
          "sha256": "0f2875d7039cb6e07fa7e17c6b91ac662392134c4fbc4bb96916d501d0a8e1f3",
          "sha1": "e5e2a828666dc967e446eee048fc591671e3a5ae",
          "md5": "808b63c9a87025e011592454c09680dd"
        }
      ]
    }
  ]
}
