{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.3.0/lib-0.3.0.module",
    "group": "com.glureau.k2d",
    "module": "lib",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-iossimulatorarm64-0.3.0.klib",
          "size": 9160,
          "sha512": "8227dd45a7fe6035427af1673ce964fe0a5603d358cdfe111f50348e5f13eecce8450f8dc59bb2c98139f13b18ab1d29d2646af6e422db304dd389b365317aae",
          "sha256": "347dc3f8d4ca7400d6a3b48fda89c5aa29e40090e2cc07d280c97400b755e393",
          "sha1": "b0a2114d693beaefe216f09130907e737a75f643",
          "md5": "6110275082ea656efa5084c15cf3ddf6"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib-iossimulatorarm64-0.3.0-metadata.jar",
          "url": "lib-iossimulatorarm64-0.3.0-metadata.jar",
          "size": 261,
          "sha512": "c914663b14630b00bd7b61ee027786ecd15ebf81085415be6ef4860095e9a942be1d3207cb6a43f5246368acbf99c3822ce5e64f1ec2c9332dbdd75a82931ac1",
          "sha256": "b3927f839acb3473e7c774d84cbd76e895e70a94cc424c7d6bd61234643354e4",
          "sha1": "22365bc705634efa166ac704285dab5daa22e348",
          "md5": "11b44716a093a7ef98f466fb62700c65"
        }
      ]
    }
  ]
}
