{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.4.4/lib-0.4.4.module",
    "group": "com.glureau.k2d",
    "module": "lib",
    "version": "0.4.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib-js-0.4.4.klib",
          "url": "lib-js-0.4.4.klib",
          "size": 11649,
          "sha512": "c5ae28cd2dd520762d51e7e323c1e8c7c750f62e85a24a3f46361c40932af3f21277b81d0d0c1cda13d7aecbeef0e25f41e306a5a493ae14a05e8357da797edc",
          "sha256": "c7373c460b0d84adece29c302cd0018d0012c8b12dc61f68e731f9fb9826cec7",
          "sha1": "e9ce9004f4c6adea15f3778b7eb3000bd986c8cc",
          "md5": "07dd75f650a5bdbedb8a8774e3e3b2a3"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib-js-0.4.4.klib",
          "url": "lib-js-0.4.4.klib",
          "size": 11649,
          "sha512": "c5ae28cd2dd520762d51e7e323c1e8c7c750f62e85a24a3f46361c40932af3f21277b81d0d0c1cda13d7aecbeef0e25f41e306a5a493ae14a05e8357da797edc",
          "sha256": "c7373c460b0d84adece29c302cd0018d0012c8b12dc61f68e731f9fb9826cec7",
          "sha1": "e9ce9004f4c6adea15f3778b7eb3000bd986c8cc",
          "md5": "07dd75f650a5bdbedb8a8774e3e3b2a3"
        }
      ]
    }
  ]
}
