{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.3.0/lib-0.3.0.module",
    "group": "com.glureau.k2d",
    "module": "lib",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-watchosarm64-0.3.0.klib",
          "size": 9110,
          "sha512": "5fbd99613386ece0f61e9342c84415a663d103cd1a5191df97975252542541f09897f30c75af76563a3ef201700ef24e8f91c96cde18696e2cbcc4b00fe2e199",
          "sha256": "0751360a5f5487b33a35a352462695e280e6a841148e298199942372421482ee",
          "sha1": "48a68deaf49800595ea4ef9844a5163ae70b6542",
          "md5": "9179ae9f81da782381f0abb79ecbe1d2"
        }
      ]
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib-watchosarm64-0.3.0-metadata.jar",
          "url": "lib-watchosarm64-0.3.0-metadata.jar",
          "size": 261,
          "sha512": "3413f3f5a2cb9fc6246aec613610b50fe6fe75b5c40d036c8a2ffc449b3752b15184e19f2a97d53b249550cc21a6bb9093564a7a64dc1023cdf4c6831f6852ec",
          "sha256": "351fc06540133cef5741d69ccec3181f9b4ce26393252fb419494583e9181260",
          "sha1": "5ba3a7c4796df12d590e1dc0afa9b5e46c9d232c",
          "md5": "efe590a3aed31cd8f0c0e1ca998228e3"
        }
      ]
    }
  ]
}
