{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.3.0/lib-0.3.0.module",
    "group": "com.glureau.k2d",
    "module": "lib",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-watchosarm64-0.3.0.klib",
          "size": 9110,
          "sha512": "5fbd99613386ece0f61e9342c84415a663d103cd1a5191df97975252542541f09897f30c75af76563a3ef201700ef24e8f91c96cde18696e2cbcc4b00fe2e199",
          "sha256": "0751360a5f5487b33a35a352462695e280e6a841148e298199942372421482ee",
          "sha1": "48a68deaf49800595ea4ef9844a5163ae70b6542",
          "md5": "9179ae9f81da782381f0abb79ecbe1d2"
        }
      ]
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib-watchosarm64-0.3.0-metadata.jar",
          "url": "lib-watchosarm64-0.3.0-metadata.jar",
          "size": 261,
          "sha512": "e4e3f1585e02174fc00620d4cf06b22116c8a2b0f1e65f0f7214585ba49a4b858a821c522fa6bcb858124ed02338e81c49cc6c320f3861ea4a2ceafdacf1db9f",
          "sha256": "3cbd7df5f3e51433ec719fdf8be91838553970d3e9b2d96ec98e8cbc7c3d0751",
          "sha1": "24cff9b82ee0167c159a53d5107e4ea370ea3393",
          "md5": "1e6ccc09f4258167246a8761c5c4e4cb"
        }
      ]
    }
  ]
}
