{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.3.0/lib-0.3.0.module",
    "group": "com.glureau.k2d",
    "module": "lib",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-watchosarm64-0.3.0.klib",
          "size": 9110,
          "sha512": "5fbd99613386ece0f61e9342c84415a663d103cd1a5191df97975252542541f09897f30c75af76563a3ef201700ef24e8f91c96cde18696e2cbcc4b00fe2e199",
          "sha256": "0751360a5f5487b33a35a352462695e280e6a841148e298199942372421482ee",
          "sha1": "48a68deaf49800595ea4ef9844a5163ae70b6542",
          "md5": "9179ae9f81da782381f0abb79ecbe1d2"
        }
      ]
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib-watchosarm64-0.3.0-metadata.jar",
          "url": "lib-watchosarm64-0.3.0-metadata.jar",
          "size": 261,
          "sha512": "efbce2a2570e0b121917a9239a8a39fa0900d085caabe920b35b88274ef8c97d359dc757ce5f39ed969c553e52aa5464b8bc9e4ce6e5d2e75eac1de8659653e3",
          "sha256": "97975c0e52193ed97de7ea7238a641bacc99f560e8d0cd430b09381ed215277c",
          "sha1": "a8b463236e1ad9b3ecec854bc2994ad42dc05f6d",
          "md5": "536d60e615cdf7638baa4a31469728a1"
        }
      ]
    }
  ]
}
