{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.1.0/lib-0.1.0.module",
    "group": "com.glureau.mermaidksp",
    "module": "lib",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-tvosx64-0.1.0.klib",
          "size": 4600,
          "sha512": "c3634596b2925a8910563469fff781168f3f742228bd360f48b8978d40d675d110e102ff480918f548d5080af0df68ff30ce6525c5d91549e42145c47b47e726",
          "sha256": "fdf5a7fc726090082ec5e30ab7e3772b41d331f48e41484c0431620fccf5cc59",
          "sha1": "fb33443c6196b11da2ed7d6146385b980462d923",
          "md5": "4f083667337bf28a1e491d68ec2884ca"
        }
      ]
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "lib-tvosx64-0.1.0-metadata.jar",
          "url": "lib-tvosx64-0.1.0-metadata.jar",
          "size": 261,
          "sha512": "096f8237cfe13e3f6d7c3f3ce63752cf145e0c7ddd9c9aa522a61c80fbe546a165225aeb8525e83c4645efef4fa5f9188d25914c23cb8f82efa516743209ed77",
          "sha256": "21869e16fbae77dfe243b06366a11957e9d7fa72823cdc2c2f1b9481fec0e9e1",
          "sha1": "374202c74911cf282dbbad05de7c95f59748cb0c",
          "md5": "822d62d73b51c4e9314155a57216e7e1"
        }
      ]
    }
  ]
}
