{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.4.1/lib-0.4.1.module",
    "group": "com.glureau.k2d",
    "module": "lib",
    "version": "0.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-watchosarm64-0.4.1.klib",
          "size": 9121,
          "sha512": "1dc2aed369a5e6c3de47e60b01e7a8b33fcb7145a40d4a3d95c9cc89abf7c1dd9d72a7b558e6dd49c81b850e29478c20e1a757d24df84eeac52376bde0b9de23",
          "sha256": "1d46b430333024c1f18e492e88aa5c50248f7a640efd91fd34ba9c49dd934b84",
          "sha1": "d8dea849d29046f6e62dff4fe67d84d080be70d8",
          "md5": "f3342f0b5b3d4a4f1986079d5b86d416"
        }
      ]
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-watchosarm64-0.4.1-metadata.jar",
          "url": "lib-watchosarm64-0.4.1-metadata.jar",
          "size": 261,
          "sha512": "0e127dd7b30dfe4d8d903eb648b37e140376a1e17000649e5bcae35079a3c370e084cd730cc12fc6d0b1a8512d8e14a22aabc987ebedf96373b80195cace59af",
          "sha256": "edfc9acb444163bb0c0df2f5bd2780fdcd4c287ece118c7764ca1f587c46c054",
          "sha1": "97a646cd334f433ad3881887741b6493834938da",
          "md5": "d5ed2eb12a4cf2ff4a9a39ce64edf938"
        }
      ]
    }
  ]
}
