{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.4.1/lib-0.4.1.module",
    "group": "com.glureau.k2d",
    "module": "lib",
    "version": "0.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-iosx64-0.4.1.klib",
          "size": 9069,
          "sha512": "12f1c8ea1dbde1500a84554a8d20c009232703887404e3749bbe4dab837aa283a3a2994ae15c2c798ff40415d32b832cee8994566a1facb9b2e149e29c7ef3a3",
          "sha256": "b8cc8ed67c38d52fe060c641fb5a08241e931da77028cbf4aa7022fa86c8c69d",
          "sha1": "9c4c22602692c19457b8cf50b64b1612d88df27c",
          "md5": "0011ace9fdc5b446f69b8b63dcfe0c8a"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-iosx64-0.4.1-metadata.jar",
          "url": "lib-iosx64-0.4.1-metadata.jar",
          "size": 261,
          "sha512": "75eaefb7b8c0a7060e1f9aa05937de8e8b363c808f038a4a556f746c10dc4539c12ce1cdae4b7135b3ba88ab14fc34777cf00f069e08f4dbf7ae6271def000fc",
          "sha256": "fa92999e21866d6a062e006b1250af3b54346106607c678bd9ea8a8f6535f510",
          "sha1": "7a84f2540e52a14a5fe0269c2853859369513679",
          "md5": "e28d9bc1fe1b29e20e5e489581fec737"
        }
      ]
    }
  ]
}
