{
  "formatVersion": "1.1",
  "component": {
    "group": "com.glureau.k2d",
    "module": "compiler",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "compiler-0.3.0.jar",
          "url": "compiler-0.3.0.jar",
          "size": 159907,
          "sha512": "4bc3b16de4343700552a74549eada2ee5f27a5a7cdb38d6cf31d3aca997447248bdc787e7d5d16a1b9fb664c9e9898fa77f359edffd0dbc6de1f9fdbaf0155de",
          "sha256": "6340c8e7ca29a2f189d49253f7feded5c0d0b6435b42640d8107d676b25ba3df",
          "sha1": "91f8a6502a0db695892fa7faa0976e24f64955dc",
          "md5": "2d258c63e2e9c86268fce26c013cafd6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.glureau.k2d",
          "module": "lib",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-ksp",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing",
          "version": {
            "requires": "1.7.10-1.0.6"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "1.7.10-1.0.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "compiler-0.3.0.jar",
          "url": "compiler-0.3.0.jar",
          "size": 159907,
          "sha512": "4bc3b16de4343700552a74549eada2ee5f27a5a7cdb38d6cf31d3aca997447248bdc787e7d5d16a1b9fb664c9e9898fa77f359edffd0dbc6de1f9fdbaf0155de",
          "sha256": "6340c8e7ca29a2f189d49253f7feded5c0d0b6435b42640d8107d676b25ba3df",
          "sha1": "91f8a6502a0db695892fa7faa0976e24f64955dc",
          "md5": "2d258c63e2e9c86268fce26c013cafd6"
        }
      ]
    }
  ]
}
