{
  "formatVersion": "1.1",
  "component": {
    "group": "com.glureau.k2d",
    "module": "compiler",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "compiler-0.3.0.jar",
          "url": "compiler-0.3.0.jar",
          "size": 159907,
          "sha512": "488157bfe8604db7882e5433b55fa7b68f78a72b96745722fc0884932d67d4a7c50d684910b9ae8dc57bc43b24a681992f86ac862af08093114499713d6f9468",
          "sha256": "d1b96bc49f59895f3e7bb776bbc70886505d7a5727ed4da8d0b673758f1abdba",
          "sha1": "6d8a2d2960221ad7e973434d940536fbb99dd5b5",
          "md5": "1e4e2f7e4ca371532fb9254d945efde8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.glureau.k2d",
          "module": "lib",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-ksp",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing",
          "version": {
            "requires": "1.7.10-1.0.6"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "1.7.10-1.0.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "compiler-0.3.0.jar",
          "url": "compiler-0.3.0.jar",
          "size": 159907,
          "sha512": "488157bfe8604db7882e5433b55fa7b68f78a72b96745722fc0884932d67d4a7c50d684910b9ae8dc57bc43b24a681992f86ac862af08093114499713d6f9468",
          "sha256": "d1b96bc49f59895f3e7bb776bbc70886505d7a5727ed4da8d0b673758f1abdba",
          "sha1": "6d8a2d2960221ad7e973434d940536fbb99dd5b5",
          "md5": "1e4e2f7e4ca371532fb9254d945efde8"
        }
      ]
    }
  ]
}
