{
  "formatVersion": "1.1",
  "component": {
    "group": "com.glureau.k2d",
    "module": "compiler",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "compiler-0.3.0.jar",
          "url": "compiler-0.3.0.jar",
          "size": 159907,
          "sha512": "25e7ccf5431fb3e20154887a8829ed766dfadc5e6e8ad6f1639b3aa4959ccdfe75a424e3ac7b7c6ee0223bc137a2c7ee7edfd413e09c42816cddb1a78a2c6055",
          "sha256": "117242724cde0f3fb2e3a39dfaa61940ad592e1d7f4ad307d19b849783f606c9",
          "sha1": "af32a9c85bf480f93e39b0be5b6ce88c7fae8f36",
          "md5": "afa6b152576c1c7400e5df09660ea6da"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.glureau.k2d",
          "module": "lib",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-ksp",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing",
          "version": {
            "requires": "1.7.10-1.0.6"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "1.7.10-1.0.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "compiler-0.3.0.jar",
          "url": "compiler-0.3.0.jar",
          "size": 159907,
          "sha512": "25e7ccf5431fb3e20154887a8829ed766dfadc5e6e8ad6f1639b3aa4959ccdfe75a424e3ac7b7c6ee0223bc137a2c7ee7edfd413e09c42816cddb1a78a2c6055",
          "sha256": "117242724cde0f3fb2e3a39dfaa61940ad592e1d7f4ad307d19b849783f606c9",
          "sha1": "af32a9c85bf480f93e39b0be5b6ce88c7fae8f36",
          "md5": "afa6b152576c1c7400e5df09660ea6da"
        }
      ]
    }
  ]
}
