{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.4.0/lib-0.4.0.module",
    "group": "com.glureau.k2d",
    "module": "lib",
    "version": "0.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-iosarm64-0.4.0.klib",
          "size": 9086,
          "sha512": "9bd3e003deb482bb0dfe99de17200bba63ececdaf17b0e4282d8ecc5321eb8a71ca99153f6645ac73cb33aa0cea50d5cdeeca47a5f8617ad6c49a2a402fb76e3",
          "sha256": "de77c0f55afa8f3d7354fffb5b8c3a82651c22152b33be1f221ae59aa4789224",
          "sha1": "c3541431608fd47513ae3264b551233f088669ec",
          "md5": "01ab1004902cdb76e4d1ef3d8bf0e953"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-iosarm64-0.4.0-metadata.jar",
          "url": "lib-iosarm64-0.4.0-metadata.jar",
          "size": 261,
          "sha512": "b56ee50a2ffdaf6166a42998294cf7f6b3d18bd806eff99f2242a6119c0ccb90bb73f29abf926bc7f9a2e155edce93c637d253ab21d477edcb20d5f37249ac95",
          "sha256": "7e2838df68fece9f3b2ff16f37cc34f4e50e3eca5ae7a40b55e0fc687ee4d4b6",
          "sha1": "d0e7876d0b4b841c9abd38bf4bcdc3fcf998d844",
          "md5": "962e70cb0bbae509d81a437b45226f29"
        }
      ]
    }
  ]
}
