{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.4.0/lib-0.4.0.module",
    "group": "com.glureau.k2d",
    "module": "lib",
    "version": "0.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-watchosx64-0.4.0.klib",
          "size": 9105,
          "sha512": "659913c00241aafff3bf747226f0ed6f70a3c5d006f4b46bad6f173dcb270c8e1cc847cbef92174e7cb0ee773042f1e8a2373c7bdc3a8a6a7e146b44045a2b2a",
          "sha256": "f6d3176793df3d5a610f6a4be50afd899d27095715054f562b2166686b363b67",
          "sha1": "d2de4ded322d14c641d8e52f9b7b747efd6f02ea",
          "md5": "de32ad260d1398719035edaf693eac66"
        }
      ]
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-watchosx64-0.4.0-metadata.jar",
          "url": "lib-watchosx64-0.4.0-metadata.jar",
          "size": 261,
          "sha512": "288b6928500dce2b25fca125910a6dd3801beb83f01f8aaa9ea34b466dc363cf8b3e1181919f11413025ae046e60862c2416155465ed507abad7da0561e72406",
          "sha256": "2906eff4ffa7057dbc91c9a243be2e953e314c7a5847ec18acd3553d543bfea4",
          "sha1": "166e8663853e8358f4a8a2274276d090c67201cf",
          "md5": "9322b30b2c6509814b4ceb19f20e595e"
        }
      ]
    }
  ]
}
