{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.4.0/lib-0.4.0.module",
    "group": "com.glureau.k2d",
    "module": "lib",
    "version": "0.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-watchosx64-0.4.0.klib",
          "size": 9105,
          "sha512": "659913c00241aafff3bf747226f0ed6f70a3c5d006f4b46bad6f173dcb270c8e1cc847cbef92174e7cb0ee773042f1e8a2373c7bdc3a8a6a7e146b44045a2b2a",
          "sha256": "f6d3176793df3d5a610f6a4be50afd899d27095715054f562b2166686b363b67",
          "sha1": "d2de4ded322d14c641d8e52f9b7b747efd6f02ea",
          "md5": "de32ad260d1398719035edaf693eac66"
        }
      ]
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-watchosx64-0.4.0-metadata.jar",
          "url": "lib-watchosx64-0.4.0-metadata.jar",
          "size": 261,
          "sha512": "5874cd4fd20a8989a0e9652e8f18200c89c8280f9adebdf6358a6317ab5e7362ae6fcf0785cb963133efca676405b9ddc639e42a8685b43334341131463041cd",
          "sha256": "d189a98373c742cf58d3d205d96518b18a3ed0d81cf27f7654b5267834691d87",
          "sha1": "9d3151ed50b745a4717f41824cd1ae207db3d92b",
          "md5": "ea0fd812be65c6dd3dbbbaafa8f5d9a4"
        }
      ]
    }
  ]
}
