{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.4.4/lib-0.4.4.module",
    "group": "com.glureau.k2d",
    "module": "lib",
    "version": "0.4.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib-jvm-0.4.4.jar",
          "url": "lib-jvm-0.4.4.jar",
          "size": 7266,
          "sha512": "3bd4d98b1380ccfab3fe6b1da43706800961ad5115519e00d67fa7bf45593ae31396506db985c2f99730e475c291cad66c15b3edc0067e109a2c306eb4fe13bf",
          "sha256": "636659331545bfb4bdb8c2bac8def2d47f2a9cdb97d2db2b2d935298722bcbe4",
          "sha1": "7bd03db2cc3e4db5f1d794b9f9948a76e320b9a2",
          "md5": "ddf19ff2881d64054da3c718b684ab6e"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib-jvm-0.4.4.jar",
          "url": "lib-jvm-0.4.4.jar",
          "size": 7266,
          "sha512": "3bd4d98b1380ccfab3fe6b1da43706800961ad5115519e00d67fa7bf45593ae31396506db985c2f99730e475c291cad66c15b3edc0067e109a2c306eb4fe13bf",
          "sha256": "636659331545bfb4bdb8c2bac8def2d47f2a9cdb97d2db2b2d935298722bcbe4",
          "sha1": "7bd03db2cc3e4db5f1d794b9f9948a76e320b9a2",
          "md5": "ddf19ff2881d64054da3c718b684ab6e"
        }
      ]
    }
  ]
}
