{
  "formatVersion": "1.1",
  "component": {
    "group": "com.glureau.k2d",
    "module": "gradle-plugin",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.glureau.k2d",
          "module": "compiler",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-plugin-0.3.0.jar",
          "url": "gradle-plugin-0.3.0.jar",
          "size": 5942,
          "sha512": "73e42ec1e393658495ba6bd06fa1566ab620a1c537cc1983b1216ec2154fa02707c6c1a872202d533f50eb06cb6914d451d857572ab9b50449b96ddbbd5ada6b",
          "sha256": "f7463c128803d2f1cc65c2194e0fc9149229ce41bc338b24d433d5cf22040982",
          "sha1": "57be2a8f1d8100f1220620a98752f90aae289930",
          "md5": "a9f642bf6187fee8eb085b96453c0725"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-gradle-plugin",
          "version": {
            "requires": "1.7.10-1.0.6"
          }
        },
        {
          "group": "com.glureau.k2d",
          "module": "lib",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "com.glureau.k2d",
          "module": "compiler",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-plugin-0.3.0.jar",
          "url": "gradle-plugin-0.3.0.jar",
          "size": 5942,
          "sha512": "73e42ec1e393658495ba6bd06fa1566ab620a1c537cc1983b1216ec2154fa02707c6c1a872202d533f50eb06cb6914d451d857572ab9b50449b96ddbbd5ada6b",
          "sha256": "f7463c128803d2f1cc65c2194e0fc9149229ce41bc338b24d433d5cf22040982",
          "sha1": "57be2a8f1d8100f1220620a98752f90aae289930",
          "md5": "a9f642bf6187fee8eb085b96453c0725"
        }
      ]
    }
  ]
}
