{
  "formatVersion": "1.1",
  "component": {
    "group": "com.glureau.k2d",
    "module": "gradle-plugin",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.glureau.k2d",
          "module": "compiler",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-plugin-0.3.0.jar",
          "url": "gradle-plugin-0.3.0.jar",
          "size": 5942,
          "sha512": "5c72e9d79d45d8a175c308c6dc46136d8ac3fe8bc788c47637aec97f1b57b5e7968a2f1596ea49dbc00f8d9694e6dc965e218b4ba95971f14db17ae15ddbd72a",
          "sha256": "2f517bdbdfdae1c6fc3ce2016f9ac36488183dae4c806cf6c4268daf33f882ba",
          "sha1": "70d693147771ffb249c498af761f9d37da4a46e2",
          "md5": "8503c0c7816ec30f9743c50a13324917"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-gradle-plugin",
          "version": {
            "requires": "1.7.10-1.0.6"
          }
        },
        {
          "group": "com.glureau.k2d",
          "module": "lib",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "com.glureau.k2d",
          "module": "compiler",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-plugin-0.3.0.jar",
          "url": "gradle-plugin-0.3.0.jar",
          "size": 5942,
          "sha512": "5c72e9d79d45d8a175c308c6dc46136d8ac3fe8bc788c47637aec97f1b57b5e7968a2f1596ea49dbc00f8d9694e6dc965e218b4ba95971f14db17ae15ddbd72a",
          "sha256": "2f517bdbdfdae1c6fc3ce2016f9ac36488183dae4c806cf6c4268daf33f882ba",
          "sha1": "70d693147771ffb249c498af761f9d37da4a46e2",
          "md5": "8503c0c7816ec30f9743c50a13324917"
        }
      ]
    }
  ]
}
