{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.3.0/lib-0.3.0.module",
    "group": "com.glureau.k2d",
    "module": "lib",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-iosarm64-0.3.0.klib",
          "size": 9074,
          "sha512": "b3c7a312fbcbbc7ff6b6e79f6f4759b1e5f131a1f045eceae1e744392309302ef8ca26e12cfaa6ed6f6730813e4514f18dd65646e1c2053c8185754cc0b4e30f",
          "sha256": "34804472a6c5f402436c57ebe6776de08478b03ba71817fa44d543fdf439e234",
          "sha1": "66aca063ffa64b46491fa410ed9fc9057a86c7b1",
          "md5": "343f9d557fbb0e9247334d4e685f604a"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib-iosarm64-0.3.0-metadata.jar",
          "url": "lib-iosarm64-0.3.0-metadata.jar",
          "size": 261,
          "sha512": "e6d42158550ce8d51b0191b65a1489edb10fc76063f1d55baf5bf1fb1408193215f311a7c6c9cb05ee009acca11590a292ebefd13000ca4519b10529cf45bc32",
          "sha256": "dc81eb53149ea72872676133ae7f4159c4afe97b94d4818cbf989d554e10dfd7",
          "sha1": "7503cc075c94d91c0b723f61e08abcd4eed85574",
          "md5": "b4238fc447061ff9a73c112accba108a"
        }
      ]
    }
  ]
}
