{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.3.0/lib-0.3.0.module",
    "group": "com.glureau.k2d",
    "module": "lib",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-iosarm64-0.3.0.klib",
          "size": 9074,
          "sha512": "b3c7a312fbcbbc7ff6b6e79f6f4759b1e5f131a1f045eceae1e744392309302ef8ca26e12cfaa6ed6f6730813e4514f18dd65646e1c2053c8185754cc0b4e30f",
          "sha256": "34804472a6c5f402436c57ebe6776de08478b03ba71817fa44d543fdf439e234",
          "sha1": "66aca063ffa64b46491fa410ed9fc9057a86c7b1",
          "md5": "343f9d557fbb0e9247334d4e685f604a"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib-iosarm64-0.3.0-metadata.jar",
          "url": "lib-iosarm64-0.3.0-metadata.jar",
          "size": 261,
          "sha512": "587ddb0aea9f3ee4d073b62f8e6664cdb4477be96b93531adf43a7cb6ef362d52e71054c0f2bedebb605ca8df9434a1a5bc4924b6cebafad29ae148e66c6c2e3",
          "sha256": "0f2875d7039cb6e07fa7e17c6b91ac662392134c4fbc4bb96916d501d0a8e1f3",
          "sha1": "e5e2a828666dc967e446eee048fc591671e3a5ae",
          "md5": "808b63c9a87025e011592454c09680dd"
        }
      ]
    }
  ]
}
