{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.4.0/lib-0.4.0.module",
    "group": "com.glureau.k2d",
    "module": "lib",
    "version": "0.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-iossimulatorarm64-0.4.0.klib",
          "size": 9171,
          "sha512": "66a3f98dfac2232c33ee14f66d157d5fb8d60eed42eab98952fca5b6462d02b352b4f79f910bc3fedb2ed9fd3651b9f139faa9e23785032200272813bb974cdd",
          "sha256": "e9fe3e4ad000271fba011d3f1bb1562925e7a2aba800c7b9746a0afad712fed5",
          "sha1": "2f95eacaea4acb658e278a8a7b11b41c7ad1f0b9",
          "md5": "c242082eacfa1af74d067f0282169f56"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-iossimulatorarm64-0.4.0-metadata.jar",
          "url": "lib-iossimulatorarm64-0.4.0-metadata.jar",
          "size": 261,
          "sha512": "8c6b21b7d16506adf9e67f8460b58f7fcee8d0d26ef175ca16e07f38a2e1f0565a84e2e42908ce54c3eba3c04d3ecee13e8a5b59b104db745a4a67ccb2a7e133",
          "sha256": "6ef91e15f8710c1a4db5f7273dc2162a9c6dbc5bd0a94346df06a868fe8ec0ec",
          "sha1": "9e72daf166e10a566484405e3d17ffb65e0a0a20",
          "md5": "5413f796486b8491987e6298011873df"
        }
      ]
    }
  ]
}
