{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.4.2/lib-0.4.2.module",
    "group": "com.glureau.k2d",
    "module": "lib",
    "version": "0.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib-release.aar",
          "url": "lib-android-0.4.2.aar",
          "size": 5229,
          "sha512": "0ddae3f06c9b114d5e09b0a6bf342c65c0a28269e7c669e2bd70f4744e11456346e461dccfd247db299062f199e50925480144b65b14bd606b6cf9d0285c4d3a",
          "sha256": "62db5d944723c9c679f89d5f92c92e7061c9517a56269c70bde448b7f224e16b",
          "sha1": "c539ed300cd31a1b0c0d395d26bef5a3078d80c5",
          "md5": "f6c61101aae696b496e0999769e4da11"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "lib-release.aar",
          "url": "lib-android-0.4.2.aar",
          "size": 5229,
          "sha512": "0ddae3f06c9b114d5e09b0a6bf342c65c0a28269e7c669e2bd70f4744e11456346e461dccfd247db299062f199e50925480144b65b14bd606b6cf9d0285c4d3a",
          "sha256": "62db5d944723c9c679f89d5f92c92e7061c9517a56269c70bde448b7f224e16b",
          "sha1": "c539ed300cd31a1b0c0d395d26bef5a3078d80c5",
          "md5": "f6c61101aae696b496e0999769e4da11"
        }
      ]
    }
  ]
}
