{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.4.3/lib-0.4.3.module",
    "group": "com.glureau.k2d",
    "module": "lib",
    "version": "0.4.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1"
    }
  },
  "variants": [
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-watchosarm64-0.4.3.klib",
          "size": 11231,
          "sha512": "249f5251266963cbcd31c498500a5a21e48c68b121c8705cbf6de7626f71b9d31545c803a5ca60c088b3366080e5486442ea1d927606f206030833cc9f80f45c",
          "sha256": "d116f570815cd9da6e4298660a082e235927c8ec7645a899aa91554e9ab6420d",
          "sha1": "bee097b4243e2cc507205531aecf8392989447b7",
          "md5": "a3f05644181201db26f8024ad514ed9b"
        }
      ]
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib-watchosarm64-0.4.3-metadata.jar",
          "url": "lib-watchosarm64-0.4.3-metadata.jar",
          "size": 261,
          "sha512": "4341e1970f242e741544d0a80b9a151a06abdd2be33ff94223561535cde97e2deb69c8399b7a14691d671c874ac149be38c80b8ca028d1ac67b135eabefe2f7a",
          "sha256": "e594f375e1ab290da457944c76436a91a08a57cd3641644c9c77e2d401411dfb",
          "sha1": "82a55d80256ec0cea581e2ddc7e6809ddff9a0e8",
          "md5": "7a5903c1a260e6b81a60e70b717c786e"
        }
      ]
    }
  ]
}
