{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.4.4/lib-0.4.4.module",
    "group": "com.glureau.k2d",
    "module": "lib",
    "version": "0.4.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-macosarm64-0.4.4.klib",
          "size": 12732,
          "sha512": "84b143c793c1e98378346266aeb830e2b923ca718de77ffd02beb1a58287220cfab5fe96be7a82e1040bd2ec9cc9effc86b746f82945745c97e626a8fb4fb413",
          "sha256": "21f2505114f03d8f4a29cc360583966332eb28e9bf541eec6ef5ca0c238381a9",
          "sha1": "33f9bbf3f60015e498101625009ae12e20985c01",
          "md5": "c8c9d1a26466cc6e97de8f1714cb4e7d"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib-macosarm64-0.4.4-metadata.jar",
          "url": "lib-macosarm64-0.4.4-metadata.jar",
          "size": 261,
          "sha512": "1fb04fa41cd017abd86bf292ff35510234fe44278b83d578b22b1a57c87725ee7a7bcc078b368ac2403b38740d795e0da0593cfb9124a3ba9f150b2ba7382c74",
          "sha256": "afa669946d67fed1293e6ac4ff1661141f7df4a679621b1ff080cbe350d1756e",
          "sha1": "5f82f72df1a8c0b22befaeaf0446e70962a4bf4c",
          "md5": "89da8a409808b9738964d513cfec567b"
        }
      ]
    }
  ]
}
