{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.4.4/lib-0.4.4.module",
    "group": "com.glureau.k2d",
    "module": "lib",
    "version": "0.4.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-iosarm64-0.4.4.klib",
          "size": 12714,
          "sha512": "86c75a0f738898e5da34cdf22556ff997b7adb8eeb03486757155effcaefed1ad7119654811e49e502a03930c54ec6e4ec69616b96cd6dcb7e77c615430a0e75",
          "sha256": "43c41ebc5946fc9cbd1d275de8edfb89c8f9f1fbb6aa036d253b4bbabcb0ac5e",
          "sha1": "fb901b8d90cc1576a378a9741e1deae26bd3ca33",
          "md5": "50ffefbf27874556fcd419001a61fce4"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib-iosarm64-0.4.4-metadata.jar",
          "url": "lib-iosarm64-0.4.4-metadata.jar",
          "size": 261,
          "sha512": "8dd580e6bf75094e1a1caa9cb174931f2e77c383c800bf8bc35bd31236bb46a9e9f1e9b91d95393dd0f4d5ca3270a32d53245f138d43ef69c0dd2037fd93f7be",
          "sha256": "534cc100b8cfcd29bcb15939606e8c28d053830bebbd808bf660c2a47b4683bc",
          "sha1": "d6b580a6d061a0e2584b286aa8eabbb1196ca5ae",
          "md5": "b1b9376e0090f5ee72aed52f71a02fa9"
        }
      ]
    }
  ]
}
