{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.4.0/lib-0.4.0.module",
    "group": "com.glureau.k2d",
    "module": "lib",
    "version": "0.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-tvosx64-0.4.0.klib",
          "size": 9078,
          "sha512": "bda687506bf06efc736e379409bd38861b73176ec00b157b0db2b48d2534af9ad4ee89f2d66f00454ae59042261a7207e11ba5b01b8c0b9a8c8154314db6df6a",
          "sha256": "27ccb02b1c697f0e8b9b47d9798005dc1f40f8e7e09fd62e1e909cf6664f3dde",
          "sha1": "02c20fe14857778747c0bc16dba932cbb22a18a5",
          "md5": "4abe50c914fc2137b1d1d988243627aa"
        }
      ]
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-tvosx64-0.4.0-metadata.jar",
          "url": "lib-tvosx64-0.4.0-metadata.jar",
          "size": 261,
          "sha512": "b2013d6dffaae7638dbcd447c7a633d5f1095b764d874bc92e51e1b01bcbd2866d9e00427f4a82407fb2fe46a626c7cfa249d0e774b79d96f95ba200b536d8d7",
          "sha256": "b0fb28611899eb3e18a824bfd6ceb4b83ea6c4066bce86b9f08563ef6bf7f4ca",
          "sha1": "5a894a20fd6eb2dab9a9e697b808b284adc9f89a",
          "md5": "2d13c78bd9962ac79f376aa26b75c1cf"
        }
      ]
    }
  ]
}
