{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.4.2/lib-0.4.2.module",
    "group": "com.glureau.k2d",
    "module": "lib",
    "version": "0.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib-js-0.4.2.klib",
          "url": "lib-js-0.4.2.klib",
          "size": 7892,
          "sha512": "14cb293c5990cc2c7ac1a0f63fdb01b057a6c191b9dadc543e9e34fd21a805946869ccdb61e01fb02ce748a5dbf3c8cca6b551ef87ba62f479fe0f4cb43705ef",
          "sha256": "10c3ab683c1232c1b9584c1df3674a0f26594233e12be9b4d73ff3594b297f66",
          "sha1": "62285dfa940b8525201bdea930f668898c3cfb42",
          "md5": "ddef9857097b05f25e0c87f767c8ca56"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib-js-0.4.2.klib",
          "url": "lib-js-0.4.2.klib",
          "size": 7892,
          "sha512": "14cb293c5990cc2c7ac1a0f63fdb01b057a6c191b9dadc543e9e34fd21a805946869ccdb61e01fb02ce748a5dbf3c8cca6b551ef87ba62f479fe0f4cb43705ef",
          "sha256": "10c3ab683c1232c1b9584c1df3674a0f26594233e12be9b4d73ff3594b297f66",
          "sha1": "62285dfa940b8525201bdea930f668898c3cfb42",
          "md5": "ddef9857097b05f25e0c87f767c8ca56"
        }
      ]
    }
  ]
}
