{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.4.3/lib-0.4.3.module",
    "group": "com.glureau.k2d",
    "module": "lib",
    "version": "0.4.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1"
    }
  },
  "variants": [
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-watchosarm32-0.4.3.klib",
          "size": 11231,
          "sha512": "e6a17833a19d1efcf68a32e09b1d04be610b92191468521083dfdfce8d9f7b0922a329235a789a80ae2e6bc94eb935e44788b0c0be3ca6d2c2fc9ffbdd33888b",
          "sha256": "dba9bdbac71167a1cdd6e8eebf50eb9041a5e0c647edfa4c860addbdae1a69db",
          "sha1": "71ee544293891d2813fb0f57cc04f2626856015c",
          "md5": "c33bdc4b43e009cbf2c8a9a14232bc43"
        }
      ]
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib-watchosarm32-0.4.3-metadata.jar",
          "url": "lib-watchosarm32-0.4.3-metadata.jar",
          "size": 261,
          "sha512": "783bac9942cdda2ce798de045736dcfeb70b57eadbe145db248b10ecb68ccc12f1b9f4ba3b0356d4742a4c378aa5b51aa338d92d4dd9a6e37f6488706499a590",
          "sha256": "b44d0f941e4bedb9f55afb60229d939930949213c231cb96a69a827c2bb150c1",
          "sha1": "e044925f85c2b210b635e3bcfaa4ad19e9f79d59",
          "md5": "d3fe34b8eeba2c2a1254ab527e683422"
        }
      ]
    }
  ]
}
