{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.4.4/lib-0.4.4.module",
    "group": "com.glureau.k2d",
    "module": "lib",
    "version": "0.4.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1"
    }
  },
  "variants": [
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-tvosx64-0.4.4.klib",
          "size": 12707,
          "sha512": "61172f641b5a415941349368dd469c3757b29591063672f381a3e5f5bc379c55e44f05aad9fc40acfa0f8e269af6acded3a1f79c9dbd4e02d1ba7638464888a5",
          "sha256": "ff73cdbea20b05853bf2871d90d23b9305f9d17a867910a40ff439b55ffc5203",
          "sha1": "682129a69d6072fcfe1e9f4fb86f96c37cb20b9a",
          "md5": "f2b45fbdc6d5d3960415a16005eca0b7"
        }
      ]
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib-tvosx64-0.4.4-metadata.jar",
          "url": "lib-tvosx64-0.4.4-metadata.jar",
          "size": 261,
          "sha512": "c62a4e2dc761f6438e91339cc368159335c0fe0aef963e1b4d9a389096fed9d1e04acdde17ec21f6255f89c7009e3eb0c02074bb00d3feb7b0a3dc5bd13a74fe",
          "sha256": "02ae87e104b64383b88719855e1f9170e17bc41502fb9faee15e6011ec4e06d2",
          "sha1": "33b09f9b5f0033435947af9aadab192392597703",
          "md5": "8d58972c471fb57d814a0324cdc08f8a"
        }
      ]
    }
  ]
}
