{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.3.0/lib-0.3.0.module",
    "group": "com.glureau.k2d",
    "module": "lib",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib-debug.aar",
          "url": "lib-android-debug-0.3.0.aar",
          "size": 5220,
          "sha512": "900590830363acf9b371e1121fe0ae7f7c5c4fb43878d173d3b66c8ff2f5524306d4fea335d3370d86a331c174d05babf8523c8f529ae7c0f47d9d3ee71b6e9b",
          "sha256": "928b152b7222b66082ef2bc85859602aba93f828feccebd4bafe01a42e11c946",
          "sha1": "37661521c9ea8e3d86ddf40a8b7e6517f7b0914c",
          "md5": "9ae76c7ea9b865f0562f2c7f1aeac691"
        }
      ]
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "lib-debug.aar",
          "url": "lib-android-debug-0.3.0.aar",
          "size": 5220,
          "sha512": "900590830363acf9b371e1121fe0ae7f7c5c4fb43878d173d3b66c8ff2f5524306d4fea335d3370d86a331c174d05babf8523c8f529ae7c0f47d9d3ee71b6e9b",
          "sha256": "928b152b7222b66082ef2bc85859602aba93f828feccebd4bafe01a42e11c946",
          "sha1": "37661521c9ea8e3d86ddf40a8b7e6517f7b0914c",
          "md5": "9ae76c7ea9b865f0562f2c7f1aeac691"
        }
      ]
    }
  ]
}
