{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.4.4/lib-0.4.4.module",
    "group": "com.glureau.k2d",
    "module": "lib",
    "version": "0.4.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1"
    }
  },
  "variants": [
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-watchosarm32-0.4.4.klib",
          "size": 12750,
          "sha512": "d601ad927644d6e14d16d7ced93a0774154df7bd569e38b79ae1a7c3d7b028cb0882c45d47d31ba63dc020ee82737a77a8abcd41f7a7dbde6c9a4a2cb8473395",
          "sha256": "f241cb7f948042adac7eebd664078c2715223fccc0cb33f1bb21840f02f51c09",
          "sha1": "21213f09857c73d2fe3c3d2ff3401a079ec1ba6b",
          "md5": "3d4f829d929433c3f5d5723656a7f137"
        }
      ]
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib-watchosarm32-0.4.4-metadata.jar",
          "url": "lib-watchosarm32-0.4.4-metadata.jar",
          "size": 261,
          "sha512": "c62a4e2dc761f6438e91339cc368159335c0fe0aef963e1b4d9a389096fed9d1e04acdde17ec21f6255f89c7009e3eb0c02074bb00d3feb7b0a3dc5bd13a74fe",
          "sha256": "02ae87e104b64383b88719855e1f9170e17bc41502fb9faee15e6011ec4e06d2",
          "sha1": "33b09f9b5f0033435947af9aadab192392597703",
          "md5": "8d58972c471fb57d814a0324cdc08f8a"
        }
      ]
    }
  ]
}
