{
  "formatVersion": "1.1",
  "component": {
    "url": "../../samples/0.4.1/samples-0.4.1.module",
    "group": "com.glureau.k2d",
    "module": "samples",
    "version": "0.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "samples-jvm-0.4.1.jar",
          "url": "samples-jvm-0.4.1.jar",
          "size": 20328,
          "sha512": "d1608d75d373b62e60836cee18b8586a73cf37ff9e55367f1ff22ed689246b6b0f1d578b408dbb38bd3483aae34498bb87cf2fac61cdf1babff68c17a832d456",
          "sha256": "f252565108df24fea3bd48702da56c878bd67b49ad48f0dbb82399f1b8f016cd",
          "sha1": "98ed216ac538c942726089c4ad39b5bb2a16ce53",
          "md5": "bb746f8c9507e6a69e8c508f86be872a"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.glureau.k2d",
          "module": "lib",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "samples-jvm-0.4.1.jar",
          "url": "samples-jvm-0.4.1.jar",
          "size": 20328,
          "sha512": "d1608d75d373b62e60836cee18b8586a73cf37ff9e55367f1ff22ed689246b6b0f1d578b408dbb38bd3483aae34498bb87cf2fac61cdf1babff68c17a832d456",
          "sha256": "f252565108df24fea3bd48702da56c878bd67b49ad48f0dbb82399f1b8f016cd",
          "sha1": "98ed216ac538c942726089c4ad39b5bb2a16ce53",
          "md5": "bb746f8c9507e6a69e8c508f86be872a"
        }
      ]
    }
  ]
}
