{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.3.0/lib-0.3.0.module",
    "group": "com.glureau.k2d",
    "module": "lib",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib-js-0.3.0.klib",
          "url": "lib-js-0.3.0.klib",
          "size": 7880,
          "sha512": "83e99c5261b35aaa7be3df073e430a63000598cae8067020a8c0a0fe27133ea0ec40a3b8560c147614417c79d8e4c3ef8f47a023b6b849b8d23608f9d04e739f",
          "sha256": "36365b3220494d18f5dfd8698e342ff35ec945c30297f63a988c3ebf69404f4b",
          "sha1": "d4b38999fe6ec4534c36ce31b9aafb3f67c75354",
          "md5": "b46577c0bfc498dbd998451839f80fe7"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib-js-0.3.0.klib",
          "url": "lib-js-0.3.0.klib",
          "size": 7880,
          "sha512": "83e99c5261b35aaa7be3df073e430a63000598cae8067020a8c0a0fe27133ea0ec40a3b8560c147614417c79d8e4c3ef8f47a023b6b849b8d23608f9d04e739f",
          "sha256": "36365b3220494d18f5dfd8698e342ff35ec945c30297f63a988c3ebf69404f4b",
          "sha1": "d4b38999fe6ec4534c36ce31b9aafb3f67c75354",
          "md5": "b46577c0bfc498dbd998451839f80fe7"
        }
      ]
    }
  ]
}
