{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.3.0/lib-0.3.0.module",
    "group": "com.glureau.k2d",
    "module": "lib",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib-js-0.3.0.klib",
          "url": "lib-js-0.3.0.klib",
          "size": 7880,
          "sha512": "55663ee0fd02bcb21fdfe2625b51fc41b2e9875ff76bfea1855230aad742f9c96e0d9aa3781658c92bb5db451c513442fe69f58035fa9329cad546151ed6e05b",
          "sha256": "935453957dc0bb8d9e64c917546dfef944f181d6bf3fffcab0270c5518120753",
          "sha1": "023eacaf4808430d1cdf05096e475549ffcb40bc",
          "md5": "f423890a45a65ecd5b134b4bc96626e4"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib-js-0.3.0.klib",
          "url": "lib-js-0.3.0.klib",
          "size": 7880,
          "sha512": "55663ee0fd02bcb21fdfe2625b51fc41b2e9875ff76bfea1855230aad742f9c96e0d9aa3781658c92bb5db451c513442fe69f58035fa9329cad546151ed6e05b",
          "sha256": "935453957dc0bb8d9e64c917546dfef944f181d6bf3fffcab0270c5518120753",
          "sha1": "023eacaf4808430d1cdf05096e475549ffcb40bc",
          "md5": "f423890a45a65ecd5b134b4bc96626e4"
        }
      ]
    }
  ]
}
