{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.3.0/lib-0.3.0.module",
    "group": "com.glureau.k2d",
    "module": "lib",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib-js-0.3.0.klib",
          "url": "lib-js-0.3.0.klib",
          "size": 7880,
          "sha512": "bf5936a6c194d11ee9a37b8a4fd6f251b1eb162a933b5b41b45c33027a5f7df557e594babdedd17b17dd9adee6ff02d4fe81b96139c8146b6952614c284e17ce",
          "sha256": "d7da8342d57c6caf4bfd2b878f3f68f4094fc48dc45d9f1a646d88430aa4fa11",
          "sha1": "411206c3fb0b94a11d6ee32aaf49e0b29242dccc",
          "md5": "63df3f551dc442adad08ddb906092060"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib-js-0.3.0.klib",
          "url": "lib-js-0.3.0.klib",
          "size": 7880,
          "sha512": "bf5936a6c194d11ee9a37b8a4fd6f251b1eb162a933b5b41b45c33027a5f7df557e594babdedd17b17dd9adee6ff02d4fe81b96139c8146b6952614c284e17ce",
          "sha256": "d7da8342d57c6caf4bfd2b878f3f68f4094fc48dc45d9f1a646d88430aa4fa11",
          "sha1": "411206c3fb0b94a11d6ee32aaf49e0b29242dccc",
          "md5": "63df3f551dc442adad08ddb906092060"
        }
      ]
    }
  ]
}
