{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.4.0/lib-0.4.0.module",
    "group": "com.glureau.k2d",
    "module": "lib",
    "version": "0.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-watchosarm32-0.4.0.klib",
          "size": 9121,
          "sha512": "32374a59271bc5e7a8e477ecac88a9f7343dd9bf0028168448e991b2f5e1c079543fcf91e8dcb4262290ead046224b4988a8c2335f17b6b63d0a29b3f47537ca",
          "sha256": "ea77c7ad9078aca60dd40160d4206855f6a4596eb6ec39877c9ac2091b284b5b",
          "sha1": "0bd9a4663eef7f74076516e8715870b9d5c6883f",
          "md5": "db170a0608f78a8f1d204765a5ba492b"
        }
      ]
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-watchosarm32-0.4.0-metadata.jar",
          "url": "lib-watchosarm32-0.4.0-metadata.jar",
          "size": 261,
          "sha512": "c97d9758e1c1d4b16664f49fab1789fede157a0ae80222de4c5ef72cc40f3ecd888b5a71efe6083133eaa584c58e9e8b5cd931179a5923ce336167def5a483a9",
          "sha256": "523045fb3a34bc34cb989ceb301ffee2ee54fc127a97347697fb5ecc202b4c0d",
          "sha1": "8964e73bdd239d101e37de97ca2ec05e484e2112",
          "md5": "96ec5119d9f9392977e9e070c49fe3b9"
        }
      ]
    }
  ]
}
