{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.4.0/lib-0.4.0.module",
    "group": "com.glureau.k2d",
    "module": "lib",
    "version": "0.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-watchosarm32-0.4.0.klib",
          "size": 9121,
          "sha512": "32374a59271bc5e7a8e477ecac88a9f7343dd9bf0028168448e991b2f5e1c079543fcf91e8dcb4262290ead046224b4988a8c2335f17b6b63d0a29b3f47537ca",
          "sha256": "ea77c7ad9078aca60dd40160d4206855f6a4596eb6ec39877c9ac2091b284b5b",
          "sha1": "0bd9a4663eef7f74076516e8715870b9d5c6883f",
          "md5": "db170a0608f78a8f1d204765a5ba492b"
        }
      ]
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-watchosarm32-0.4.0-metadata.jar",
          "url": "lib-watchosarm32-0.4.0-metadata.jar",
          "size": 261,
          "sha512": "b2013d6dffaae7638dbcd447c7a633d5f1095b764d874bc92e51e1b01bcbd2866d9e00427f4a82407fb2fe46a626c7cfa249d0e774b79d96f95ba200b536d8d7",
          "sha256": "b0fb28611899eb3e18a824bfd6ceb4b83ea6c4066bce86b9f08563ef6bf7f4ca",
          "sha1": "5a894a20fd6eb2dab9a9e697b808b284adc9f89a",
          "md5": "2d13c78bd9962ac79f376aa26b75c1cf"
        }
      ]
    }
  ]
}
