{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.4.2/lib-0.4.2.module",
    "group": "com.glureau.k2d",
    "module": "lib",
    "version": "0.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1"
    }
  },
  "variants": [
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-watchosarm32-0.4.2.klib",
          "size": 9122,
          "sha512": "c4f3a678ce27d23eed68470de1b7614bfe83c660b295e4f81ffd11f1157b1af45580f1f9e51a2469fd3a912e13c9f31b07c6a92ea176361f1d5b56201ee2381c",
          "sha256": "eb05a84e496f06c12aa3243f282b0619ba473dccbccc4c7716b2db56c841062a",
          "sha1": "afe559b5a4e7cab6a07906e93ccd3644e41892c3",
          "md5": "7d48422ebd35aed939494d0bdb036de6"
        }
      ]
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib-watchosarm32-0.4.2-metadata.jar",
          "url": "lib-watchosarm32-0.4.2-metadata.jar",
          "size": 261,
          "sha512": "7bf0cb93e4546b05cde8cdd110da22a75309137f8b45d7d5030460f6a6bd7f171baa245f746c15a6308c19c1326fc2d7406aea610a435f3727f3ef88e536ac4b",
          "sha256": "b9c49698c6012299029df377fca1d0d3e62c768e5e915ec00cf8e5e1a9cd66fd",
          "sha1": "8a9f789d98603ef77d78962ba841013654e84508",
          "md5": "3ee8870b0a692d28b4a19f06deb60cab"
        }
      ]
    }
  ]
}
