{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.3.0/lib-0.3.0.module",
    "group": "com.glureau.k2d",
    "module": "lib",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib-jvm-0.3.0.jar",
          "url": "lib-jvm-0.3.0.jar",
          "size": 5286,
          "sha512": "d9839be0511cc690c22a75800146b4bbc8520c2b07a9d618c85f4dc1c28d705a79c27bef5556b9d8b007c1eb8ee32c012ef237efc24852877429aa04f49fc47c",
          "sha256": "34afcd5fbe7f929da03aeee0ae406cef3c869480b4234cfc42254ade1d9068c2",
          "sha1": "5dffb3528f12fbe3d612a6b876309a7130176cd0",
          "md5": "a8108f4432ea3967c1291f1122c2b4a9"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib-jvm-0.3.0.jar",
          "url": "lib-jvm-0.3.0.jar",
          "size": 5286,
          "sha512": "d9839be0511cc690c22a75800146b4bbc8520c2b07a9d618c85f4dc1c28d705a79c27bef5556b9d8b007c1eb8ee32c012ef237efc24852877429aa04f49fc47c",
          "sha256": "34afcd5fbe7f929da03aeee0ae406cef3c869480b4234cfc42254ade1d9068c2",
          "sha1": "5dffb3528f12fbe3d612a6b876309a7130176cd0",
          "md5": "a8108f4432ea3967c1291f1122c2b4a9"
        }
      ]
    }
  ]
}
