{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.3.0/lib-0.3.0.module",
    "group": "com.glureau.k2d",
    "module": "lib",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib-jvm-0.3.0.jar",
          "url": "lib-jvm-0.3.0.jar",
          "size": 5286,
          "sha512": "3bf376fbf8179fb9db3e9a547b4a1ebfc4a05c20e551bfd91ef2a47a377d2a2401eafd549ffe89a64bcb3d88c331681828e80f16437cf85f7068e4a3a36a3227",
          "sha256": "3bfa4e80bccdc69da7e97189fbcc5e114502a689690cc3dd3df16c67ca8ee3d8",
          "sha1": "4eca8bf939a21ed38c196a467c2aa229eee5521a",
          "md5": "c28752354671972b113ee81365f76f7e"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib-jvm-0.3.0.jar",
          "url": "lib-jvm-0.3.0.jar",
          "size": 5286,
          "sha512": "3bf376fbf8179fb9db3e9a547b4a1ebfc4a05c20e551bfd91ef2a47a377d2a2401eafd549ffe89a64bcb3d88c331681828e80f16437cf85f7068e4a3a36a3227",
          "sha256": "3bfa4e80bccdc69da7e97189fbcc5e114502a689690cc3dd3df16c67ca8ee3d8",
          "sha1": "4eca8bf939a21ed38c196a467c2aa229eee5521a",
          "md5": "c28752354671972b113ee81365f76f7e"
        }
      ]
    }
  ]
}
