{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.4.0/lib-0.4.0.module",
    "group": "com.glureau.k2d",
    "module": "lib",
    "version": "0.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-watchosarm64-0.4.0.klib",
          "size": 9121,
          "sha512": "1dc2aed369a5e6c3de47e60b01e7a8b33fcb7145a40d4a3d95c9cc89abf7c1dd9d72a7b558e6dd49c81b850e29478c20e1a757d24df84eeac52376bde0b9de23",
          "sha256": "1d46b430333024c1f18e492e88aa5c50248f7a640efd91fd34ba9c49dd934b84",
          "sha1": "d8dea849d29046f6e62dff4fe67d84d080be70d8",
          "md5": "f3342f0b5b3d4a4f1986079d5b86d416"
        }
      ]
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-watchosarm64-0.4.0-metadata.jar",
          "url": "lib-watchosarm64-0.4.0-metadata.jar",
          "size": 261,
          "sha512": "288b6928500dce2b25fca125910a6dd3801beb83f01f8aaa9ea34b466dc363cf8b3e1181919f11413025ae046e60862c2416155465ed507abad7da0561e72406",
          "sha256": "2906eff4ffa7057dbc91c9a243be2e953e314c7a5847ec18acd3553d543bfea4",
          "sha1": "166e8663853e8358f4a8a2274276d090c67201cf",
          "md5": "9322b30b2c6509814b4ceb19f20e595e"
        }
      ]
    }
  ]
}
