{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.4.2/lib-0.4.2.module",
    "group": "com.glureau.k2d",
    "module": "lib",
    "version": "0.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1"
    }
  },
  "variants": [
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-macosx64-0.4.2.klib",
          "size": 9088,
          "sha512": "b339e755952d02761f2ae10d69cfc49999bd915fbcdce484d493aecee3fa92ad6e637e4b43de8b6022f4a284e363e7bc6b1061ec40da6c180abe0ffb78068d07",
          "sha256": "5ddcaf59ff0fe14de6a6e97e8a8ca6b75c3af5883299f5e74a5f92604de517dc",
          "sha1": "17cd230d4143b7bc64eea77645d1f2ecd2e96b16",
          "md5": "fab0fd692b58d63ef3ecd7653944066f"
        }
      ]
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib-macosx64-0.4.2-metadata.jar",
          "url": "lib-macosx64-0.4.2-metadata.jar",
          "size": 261,
          "sha512": "364a70ff6fd28c6ecd29ed50951658b4838d930fd0ab5ae1a5a955bcef0de788571878d88ccab0f9d1db492e50d4cce314b92c6fe46987c5358641eb938be4cb",
          "sha256": "9852952eb4b7fe513e0ee2667a273ce8f614e89d9cae56d7326e3924d8c619a5",
          "sha1": "f78fe0f20c9a7658c575e43af38c35370c0af8c1",
          "md5": "cf1dc57d6c4b26e63355d9fff2b77e55"
        }
      ]
    }
  ]
}
