{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.4.0/lib-0.4.0.module",
    "group": "com.glureau.k2d",
    "module": "lib",
    "version": "0.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-macosx64-0.4.0.klib",
          "size": 9087,
          "sha512": "64ef7f317ca8826b1e74a682510771cf6b89ef4420b39048122ca34af5d4c222b86043034ae03acfcc78c7c9bf897b82d7f09d6cb7234343d8ce06b459fda22e",
          "sha256": "e523a3b5177c8b61322067a42fd1961d3af6896fe13ded58655dabec7b2057bc",
          "sha1": "309a386a6d6a2256c4188630761e158df67048ca",
          "md5": "266384fc1e8742efedf33e1841ab4dc2"
        }
      ]
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-macosx64-0.4.0-metadata.jar",
          "url": "lib-macosx64-0.4.0-metadata.jar",
          "size": 261,
          "sha512": "b2013d6dffaae7638dbcd447c7a633d5f1095b764d874bc92e51e1b01bcbd2866d9e00427f4a82407fb2fe46a626c7cfa249d0e774b79d96f95ba200b536d8d7",
          "sha256": "b0fb28611899eb3e18a824bfd6ceb4b83ea6c4066bce86b9f08563ef6bf7f4ca",
          "sha1": "5a894a20fd6eb2dab9a9e697b808b284adc9f89a",
          "md5": "2d13c78bd9962ac79f376aa26b75c1cf"
        }
      ]
    }
  ]
}
