{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.3.0/lib-0.3.0.module",
    "group": "com.glureau.k2d",
    "module": "lib",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-macosx64-0.3.0.klib",
          "size": 9075,
          "sha512": "a59a63090fa468614a687609f30d706450bb7f8d5cfd893dfb6e02196d3d9f96763e64562ac0f8ece30d0c7d0556add4f2000c9338b34b9e714659ddc56c34f2",
          "sha256": "811c45d0c860cba4e4f9c334db06b7ffd05b07aa505b2e21a17a4c092585ced9",
          "sha1": "43dfcf561a84282816b01d6bf8d6224ddb230bad",
          "md5": "e187ebc3837fec7257aa35895e568000"
        }
      ]
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib-macosx64-0.3.0-metadata.jar",
          "url": "lib-macosx64-0.3.0-metadata.jar",
          "size": 261,
          "sha512": "421c2f88dabad88dc6ee161c532b493c412c10f305343002c25cd2fbed089aac074c72ac07a760004247cb82687bc5870dbb42bfd4a0cb437882a2d7717f9b9a",
          "sha256": "81f4ec5c53928f246070a2ca7728a77d0716d7cd3b735c669b8fafbfde1014fa",
          "sha1": "adf29bf88bb0a52914d39722a386fa0e401d0eb2",
          "md5": "3871363ea59e94f27594a1081a4c5095"
        }
      ]
    }
  ]
}
