{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.3.0/lib-0.3.0.module",
    "group": "com.glureau.k2d",
    "module": "lib",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-macosx64-0.3.0.klib",
          "size": 9075,
          "sha512": "a59a63090fa468614a687609f30d706450bb7f8d5cfd893dfb6e02196d3d9f96763e64562ac0f8ece30d0c7d0556add4f2000c9338b34b9e714659ddc56c34f2",
          "sha256": "811c45d0c860cba4e4f9c334db06b7ffd05b07aa505b2e21a17a4c092585ced9",
          "sha1": "43dfcf561a84282816b01d6bf8d6224ddb230bad",
          "md5": "e187ebc3837fec7257aa35895e568000"
        }
      ]
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib-macosx64-0.3.0-metadata.jar",
          "url": "lib-macosx64-0.3.0-metadata.jar",
          "size": 261,
          "sha512": "c7dcd27539d21505492610d79f5e630d1d1a86c0ad981a368bcf3b85d1aa417b03264a154dd8e8bd8c40695f3df2fe0610270bcb317d0c66d61a82719583338c",
          "sha256": "762baa33e197c73094e46ba0c69f82c0473b68ed619341fe6f6234304805e161",
          "sha1": "2044ba0da903f22aae05459a2b9c459e145d95df",
          "md5": "53608d471442dd896f2813c183e3c0e7"
        }
      ]
    }
  ]
}
