{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.3.0/lib-0.3.0.module",
    "group": "com.glureau.k2d",
    "module": "lib",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-macosx64-0.3.0.klib",
          "size": 9075,
          "sha512": "a59a63090fa468614a687609f30d706450bb7f8d5cfd893dfb6e02196d3d9f96763e64562ac0f8ece30d0c7d0556add4f2000c9338b34b9e714659ddc56c34f2",
          "sha256": "811c45d0c860cba4e4f9c334db06b7ffd05b07aa505b2e21a17a4c092585ced9",
          "sha1": "43dfcf561a84282816b01d6bf8d6224ddb230bad",
          "md5": "e187ebc3837fec7257aa35895e568000"
        }
      ]
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib-macosx64-0.3.0-metadata.jar",
          "url": "lib-macosx64-0.3.0-metadata.jar",
          "size": 261,
          "sha512": "ff0375913ad05b4946c0e88176b1402933a0ca55dae5c67eaabe32326e34a57155d7a2faf71e78a30bd7f2d45af861d27770ed4a35f65acd4d343edeec7a6687",
          "sha256": "df36d39588687cf062deefe5071fabf338bb9f3a97187334eddb8d4de26a37dd",
          "sha1": "794ced59c2d5ffe3abc9bd943b59702aa010bf60",
          "md5": "e160d9ce11075982ad78b37cd5e7e71a"
        }
      ]
    }
  ]
}
