{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.4.0/lib-0.4.0.module",
    "group": "com.glureau.k2d",
    "module": "lib",
    "version": "0.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-iosx64-0.4.0.klib",
          "size": 9069,
          "sha512": "12f1c8ea1dbde1500a84554a8d20c009232703887404e3749bbe4dab837aa283a3a2994ae15c2c798ff40415d32b832cee8994566a1facb9b2e149e29c7ef3a3",
          "sha256": "b8cc8ed67c38d52fe060c641fb5a08241e931da77028cbf4aa7022fa86c8c69d",
          "sha1": "9c4c22602692c19457b8cf50b64b1612d88df27c",
          "md5": "0011ace9fdc5b446f69b8b63dcfe0c8a"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-iosx64-0.4.0-metadata.jar",
          "url": "lib-iosx64-0.4.0-metadata.jar",
          "size": 261,
          "sha512": "b56ee50a2ffdaf6166a42998294cf7f6b3d18bd806eff99f2242a6119c0ccb90bb73f29abf926bc7f9a2e155edce93c637d253ab21d477edcb20d5f37249ac95",
          "sha256": "7e2838df68fece9f3b2ff16f37cc34f4e50e3eca5ae7a40b55e0fc687ee4d4b6",
          "sha1": "d0e7876d0b4b841c9abd38bf4bcdc3fcf998d844",
          "md5": "962e70cb0bbae509d81a437b45226f29"
        }
      ]
    }
  ]
}
