{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.4.0/lib-0.4.0.module",
    "group": "com.glureau.k2d",
    "module": "lib",
    "version": "0.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-iosx64-0.4.0.klib",
          "size": 9069,
          "sha512": "12f1c8ea1dbde1500a84554a8d20c009232703887404e3749bbe4dab837aa283a3a2994ae15c2c798ff40415d32b832cee8994566a1facb9b2e149e29c7ef3a3",
          "sha256": "b8cc8ed67c38d52fe060c641fb5a08241e931da77028cbf4aa7022fa86c8c69d",
          "sha1": "9c4c22602692c19457b8cf50b64b1612d88df27c",
          "md5": "0011ace9fdc5b446f69b8b63dcfe0c8a"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-iosx64-0.4.0-metadata.jar",
          "url": "lib-iosx64-0.4.0-metadata.jar",
          "size": 261,
          "sha512": "2361a28c694bba99c12b5fa4d6d4665e71b80d36b4e99e09e55526df0c2d050668c69b70352d9a517368948d46d25a9e4881a191abe08e21442739458ccd506d",
          "sha256": "72af192f87655e26d0deeb0bbf675843209085bd8c75e1b55a2810fd4a4e8f29",
          "sha1": "5bd7e8b2a433be950c8de00ff1ef72392e9f9795",
          "md5": "a391d006357bf4254f62aa758b0c1e30"
        }
      ]
    }
  ]
}
