{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.4.2/lib-0.4.2.module",
    "group": "com.glureau.k2d",
    "module": "lib",
    "version": "0.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1"
    }
  },
  "variants": [
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-tvosarm64-0.4.2.klib",
          "size": 9095,
          "sha512": "9c9ec0fcaae8cb9bdcc4dcc7e420e8c1065521fd10de09982256e16f9d87e79bd66956ce8b4a7fb67c52ee3c5d5637dadb822d66dc2d0b1574c60ec1a419b8ae",
          "sha256": "8b25e3c31625c2c1771079795e16c2008b96d8b546ab2d53296b5681b0aa28f9",
          "sha1": "d723fa0ffc21ace057233adb59011fe4992a234a",
          "md5": "ff6b426194db078fd315591fce718199"
        }
      ]
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib-tvosarm64-0.4.2-metadata.jar",
          "url": "lib-tvosarm64-0.4.2-metadata.jar",
          "size": 261,
          "sha512": "a04ed6dccca765ac3981c3b80b8f107a14c9ee2f019a3303fe615c1a55ad37453f6df6d91bccb72461203583f57bd37758d92a35ef8f3d8342e8e015b1db4818",
          "sha256": "e14a2a3aa96a3a5cc9193a1dd80b4730c3d327bc011a27f6bf78b8edac130d76",
          "sha1": "1ea2d89e88e3b8edb1e3b7861b4c59c52c80f880",
          "md5": "9f16cddac61c4c7a46129982a3be1d6b"
        }
      ]
    }
  ]
}
