{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.1.0/lib-0.1.0.module",
    "group": "com.glureau.mermaidksp",
    "module": "lib",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "lib-js-0.1.0.klib",
          "url": "lib-js-0.1.0.klib",
          "size": 3502,
          "sha512": "ae3b88e1ea245a1f99c80ed689e63dddd0f27a38045f43e1c57f5f48cdba60ef2cbc96cae6d8686806a428de744cedb9a4fd83e12aa901223b4fe67bfdd281da",
          "sha256": "cfa21d55575457c298a68974e120157c5a120512b880a9885d90d563f3014aee",
          "sha1": "4d26af60741f88bb5f13bbc845563e60b098b5c3",
          "md5": "d8fb9c880f15a3e008e3d9b1d142208f"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "lib-js-0.1.0.klib",
          "url": "lib-js-0.1.0.klib",
          "size": 3502,
          "sha512": "ae3b88e1ea245a1f99c80ed689e63dddd0f27a38045f43e1c57f5f48cdba60ef2cbc96cae6d8686806a428de744cedb9a4fd83e12aa901223b4fe67bfdd281da",
          "sha256": "cfa21d55575457c298a68974e120157c5a120512b880a9885d90d563f3014aee",
          "sha1": "4d26af60741f88bb5f13bbc845563e60b098b5c3",
          "md5": "d8fb9c880f15a3e008e3d9b1d142208f"
        }
      ]
    }
  ]
}
