{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.4.2/lib-0.4.2.module",
    "group": "com.glureau.k2d",
    "module": "lib",
    "version": "0.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1"
    }
  },
  "variants": [
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib-debug.aar",
          "url": "lib-android-debug-0.4.2.aar",
          "size": 5366,
          "sha512": "dd097be6b5972472b70cf4306e45d6f7211a53a6a58ecdffb7a300cfa103bf188fbe1bc3707e96f67229eaf39070644c99149887a880901aad8155e5836fa58f",
          "sha256": "650e9ee084ab4988a66000dc0c4c48fda3a78b42df9f0706be7713e0d96dfce8",
          "sha1": "711725d8ca14e35f6fb66e4a6c6f8d29df0cb8fa",
          "md5": "323b59d2ee9692c6084125edcbf6cc9d"
        }
      ]
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "lib-debug.aar",
          "url": "lib-android-debug-0.4.2.aar",
          "size": 5366,
          "sha512": "dd097be6b5972472b70cf4306e45d6f7211a53a6a58ecdffb7a300cfa103bf188fbe1bc3707e96f67229eaf39070644c99149887a880901aad8155e5836fa58f",
          "sha256": "650e9ee084ab4988a66000dc0c4c48fda3a78b42df9f0706be7713e0d96dfce8",
          "sha1": "711725d8ca14e35f6fb66e4a6c6f8d29df0cb8fa",
          "md5": "323b59d2ee9692c6084125edcbf6cc9d"
        }
      ]
    }
  ]
}
