{
  "formatVersion": "1.1",
  "component": {
    "group": "com.glureau.k2d",
    "module": "gradle-plugin",
    "version": "0.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.glureau.k2d",
          "module": "compiler",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-plugin-0.4.0.jar",
          "url": "gradle-plugin-0.4.0.jar",
          "size": 7161,
          "sha512": "84e086930b4882e8c4ab7536771c826a0ca3716eeb36486dc5e41c16706a41de0fc5ad92c65b29635926e0460085b777551fde3327fbbc7cc75348bd493f1fa6",
          "sha256": "87c65e79c7f3f8d4d4fe21f637be71da257d5f72f5a327331653d652d90391c7",
          "sha1": "cf0bb80b978d58eee589e3dbad4ee244268e2cc8",
          "md5": "f74fcc58696a5759e7771ff878507fa1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-gradle-plugin",
          "version": {
            "requires": "1.8.0-1.0.9"
          }
        },
        {
          "group": "com.glureau.k2d",
          "module": "lib",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "com.glureau.k2d",
          "module": "compiler",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-plugin-0.4.0.jar",
          "url": "gradle-plugin-0.4.0.jar",
          "size": 7161,
          "sha512": "84e086930b4882e8c4ab7536771c826a0ca3716eeb36486dc5e41c16706a41de0fc5ad92c65b29635926e0460085b777551fde3327fbbc7cc75348bd493f1fa6",
          "sha256": "87c65e79c7f3f8d4d4fe21f637be71da257d5f72f5a327331653d652d90391c7",
          "sha1": "cf0bb80b978d58eee589e3dbad4ee244268e2cc8",
          "md5": "f74fcc58696a5759e7771ff878507fa1"
        }
      ]
    }
  ]
}
