{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.3.0/lib-0.3.0.module",
    "group": "com.glureau.k2d",
    "module": "lib",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-watchosx64-0.3.0.klib",
          "size": 9094,
          "sha512": "4951b76ea060e835551960e46729c42a9e866d196878c1e2a8fb3b89db30d465ff7ef3e56ce8a020136891ffca39059b226eae63d8e3754c9cec19412f80a385",
          "sha256": "4a760a1310b8d652168ec83707667ac677dfb6761b58162031348e0efa292a2c",
          "sha1": "ad022aa0827af33017df03f23e92ed1887f1c62f",
          "md5": "197e8065f20626ae5810c3ddbf64a79d"
        }
      ]
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib-watchosx64-0.3.0-metadata.jar",
          "url": "lib-watchosx64-0.3.0-metadata.jar",
          "size": 261,
          "sha512": "9582ea60474d758f445dd8b1abfc9ca9d04d1dda40dab098fd974a19cd1b6fa13e0e26e1c8e9287db2b6eeccce35bbc0613a828480d9159cee8ed69ca6c4b798",
          "sha256": "1cd94d3c25f96bdfbbe48ac81c63c4f5a1d195142f08c1de91b3c835d3060e97",
          "sha1": "9f7588014bd5218a56239ee32ecee4895974af97",
          "md5": "3708c260ae075e93f201b000093d35b5"
        }
      ]
    }
  ]
}
