{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.3.0/lib-0.3.0.module",
    "group": "com.glureau.k2d",
    "module": "lib",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-watchosx64-0.3.0.klib",
          "size": 9094,
          "sha512": "4951b76ea060e835551960e46729c42a9e866d196878c1e2a8fb3b89db30d465ff7ef3e56ce8a020136891ffca39059b226eae63d8e3754c9cec19412f80a385",
          "sha256": "4a760a1310b8d652168ec83707667ac677dfb6761b58162031348e0efa292a2c",
          "sha1": "ad022aa0827af33017df03f23e92ed1887f1c62f",
          "md5": "197e8065f20626ae5810c3ddbf64a79d"
        }
      ]
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib-watchosx64-0.3.0-metadata.jar",
          "url": "lib-watchosx64-0.3.0-metadata.jar",
          "size": 261,
          "sha512": "9a9c4d50f95788f805a7ffcdeb9d969202555ee4bfd93570baf5c3f292ba63aa4d54b75f0f902530fcae6370e354c7977c54c9d2e810ae343464e60af0725dfb",
          "sha256": "1c24424e5709d4c9abaae60a0179e1f40b82a2b9429f17dc09f90e4b2dce05c8",
          "sha1": "5433e0bb7b932f02b750b1d95f17431dbaeb0cfa",
          "md5": "d55b82a357a7662ca6ab73d741c594ad"
        }
      ]
    }
  ]
}
