{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.3.0/lib-0.3.0.module",
    "group": "com.glureau.k2d",
    "module": "lib",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-watchosx64-0.3.0.klib",
          "size": 9094,
          "sha512": "4951b76ea060e835551960e46729c42a9e866d196878c1e2a8fb3b89db30d465ff7ef3e56ce8a020136891ffca39059b226eae63d8e3754c9cec19412f80a385",
          "sha256": "4a760a1310b8d652168ec83707667ac677dfb6761b58162031348e0efa292a2c",
          "sha1": "ad022aa0827af33017df03f23e92ed1887f1c62f",
          "md5": "197e8065f20626ae5810c3ddbf64a79d"
        }
      ]
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib-watchosx64-0.3.0-metadata.jar",
          "url": "lib-watchosx64-0.3.0-metadata.jar",
          "size": 261,
          "sha512": "4421993c7745793d421c82e514100014eb7519657386eb0cc0507b342fbe404eb03898cfa5ea2c841d46f6328953a8a40e8d8a6fae7aad7de30b1358fdd13454",
          "sha256": "473412fe135efff5db0953ce39bfee4d90038c16a0148e8ce9061b70b733ad26",
          "sha1": "adbbe87bdc4ad1fa4c51c93dcb75a529ad1b3ec0",
          "md5": "088a327ccec72fe5a713cafe54b007bc"
        }
      ]
    }
  ]
}
