{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.3.0/lib-0.3.0.module",
    "group": "com.glureau.k2d",
    "module": "lib",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-iosx64-0.3.0.klib",
          "size": 9058,
          "sha512": "fec25e4441051cbd0239db1f6ee9b01debff4b14a067781371972b3fe3cd70a8f48a28a2ef0fa9efa59faaa20f3d004600d2677bd5f4fadba5d7f1d51690d0a4",
          "sha256": "bf3c9cc902861f3270b5e64721a81e0109f7cbb5340919c33970c359d7eeb21d",
          "sha1": "3f9f332bd17865eb02e1b6a7a315763d5586c291",
          "md5": "4e282605a85c063aba960573f74a98cf"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib-iosx64-0.3.0-metadata.jar",
          "url": "lib-iosx64-0.3.0-metadata.jar",
          "size": 261,
          "sha512": "07613d893d4c845344f04b08140dafab87f1659b8ccf718a8c70c33be8fb8732c1d860a60fdf1e18e8eecb2e6fca59b6542b7426215b1363c47a6fccfabd8fcb",
          "sha256": "fe88ee6b3a14ca506750f32cddff61e3993ad3daea996110e7f7ab2941d82c7d",
          "sha1": "17b47991d061675bee4a931384146647ff5517ec",
          "md5": "00e00f41c68a830b1c1aa5a65d9addc1"
        }
      ]
    }
  ]
}
