{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.3.0/lib-0.3.0.module",
    "group": "com.glureau.k2d",
    "module": "lib",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-iosx64-0.3.0.klib",
          "size": 9058,
          "sha512": "fec25e4441051cbd0239db1f6ee9b01debff4b14a067781371972b3fe3cd70a8f48a28a2ef0fa9efa59faaa20f3d004600d2677bd5f4fadba5d7f1d51690d0a4",
          "sha256": "bf3c9cc902861f3270b5e64721a81e0109f7cbb5340919c33970c359d7eeb21d",
          "sha1": "3f9f332bd17865eb02e1b6a7a315763d5586c291",
          "md5": "4e282605a85c063aba960573f74a98cf"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib-iosx64-0.3.0-metadata.jar",
          "url": "lib-iosx64-0.3.0-metadata.jar",
          "size": 261,
          "sha512": "a7215686cc68821465e9b940acdf15b7ab26e325889d1c1edf99b59bda1c9510dca5947de3a5b00c8a537ba58fe74b29cf23b78e572dda6d0548a81f71b723df",
          "sha256": "2ea74a9fedf351499aa8645eeae82b19da775a5b689732cd07a7bef1359638d7",
          "sha1": "059ff7bcc50adcb6a1ce7d481e47689978cc1048",
          "md5": "3915c7102a01e13b4a6a600be2df456c"
        }
      ]
    }
  ]
}
