{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.3.0/lib-0.3.0.module",
    "group": "com.glureau.k2d",
    "module": "lib",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-iosx64-0.3.0.klib",
          "size": 9058,
          "sha512": "fec25e4441051cbd0239db1f6ee9b01debff4b14a067781371972b3fe3cd70a8f48a28a2ef0fa9efa59faaa20f3d004600d2677bd5f4fadba5d7f1d51690d0a4",
          "sha256": "bf3c9cc902861f3270b5e64721a81e0109f7cbb5340919c33970c359d7eeb21d",
          "sha1": "3f9f332bd17865eb02e1b6a7a315763d5586c291",
          "md5": "4e282605a85c063aba960573f74a98cf"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib-iosx64-0.3.0-metadata.jar",
          "url": "lib-iosx64-0.3.0-metadata.jar",
          "size": 261,
          "sha512": "e6d42158550ce8d51b0191b65a1489edb10fc76063f1d55baf5bf1fb1408193215f311a7c6c9cb05ee009acca11590a292ebefd13000ca4519b10529cf45bc32",
          "sha256": "dc81eb53149ea72872676133ae7f4159c4afe97b94d4818cbf989d554e10dfd7",
          "sha1": "7503cc075c94d91c0b723f61e08abcd4eed85574",
          "md5": "b4238fc447061ff9a73c112accba108a"
        }
      ]
    }
  ]
}
